/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ClientsApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_ClientsApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_ClientsApi_H_



#include "danflix_client/ApiClient.h"

#include "danflix_client/model/Models_Client.h"
#include "danflix_client/model/Models_Command.h"
#include <map>
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ClientsApi 
{
public:

    explicit ClientsApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ClientsApi();

    /// <summary>
    /// List clients
    /// </summary>
    /// <remarks>
    /// List all registered clients
    /// </remarks>
    pplx::task<std::vector<std::shared_ptr<Models_Client>>> clientsGet(
    ) const;
    /// <summary>
    /// Send command
    /// </summary>
    /// <remarks>
    /// Send a command payload to a connected client
    /// </remarks>
    /// <param name="id">Client ID</param>
    /// <param name="command">Command</param>
    pplx::task<std::map<utility::string_t, utility::string_t>> clientsIdCommandPost(
        utility::string_t id,
        std::shared_ptr<Models_Command> command
    ) const;
    /// <summary>
    /// SSE Endpoint
    /// </summary>
    /// <remarks>
    /// Connect to receive server-sent events
    /// </remarks>
    /// <param name="id">Client ID</param>
    pplx::task<utility::string_t> clientsIdEventsGet(
        utility::string_t id
    ) const;
    /// <summary>
    /// Register a new client
    /// </summary>
    /// <remarks>
    /// Register a client device to receive commands
    /// </remarks>
    /// <param name="client">Client Info</param>
    pplx::task<std::shared_ptr<Models_Client>> clientsPost(
        std::shared_ptr<Models_Client> client
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_ClientsApi_H_ */

