/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CollectionsApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_CollectionsApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_CollectionsApi_H_



#include "danflix_client/ApiClient.h"

#include "danflix_client/model/Models_Collection.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  CollectionsApi 
{
public:

    explicit CollectionsApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~CollectionsApi();

    /// <summary>
    /// List all collections
    /// </summary>
    /// <remarks>
    /// List all collections
    /// </remarks>
    pplx::task<std::vector<std::shared_ptr<Models_Collection>>> collectionsGet(
    ) const;
    /// <summary>
    /// Get a collection
    /// </summary>
    /// <remarks>
    /// Get a collection by ID with associated Games, Movies, and TV Shows
    /// </remarks>
    /// <param name="id">Collection ID</param>
    pplx::task<std::shared_ptr<Models_Collection>> collectionsIdGet(
        utility::string_t id
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_CollectionsApi_H_ */

