/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GamesApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_GamesApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_GamesApi_H_



#include "danflix_client/ApiClient.h"

#include "danflix_client/AnyType.h"
#include "danflix_client/HttpContent.h"
#include "danflix_client/model/Models_Game.h"
#include "danflix_client/model/Routes_ImportGamesRequest.h"
#include <map>
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  GamesApi 
{
public:

    explicit GamesApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~GamesApi();

    /// <summary>
    /// Get all games
    /// </summary>
    /// <remarks>
    /// Get all games from the database
    /// </remarks>
    /// <param name="title">Filter by title (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="decade">Filter by decade (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="platform">Filter by platform (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="genre">Filter by genre (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="players">Filter by number of players (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::vector<std::shared_ptr<Models_Game>>> gamesGet(
        boost::optional<utility::string_t> title,
        boost::optional<utility::string_t> decade,
        boost::optional<utility::string_t> platform,
        boost::optional<utility::string_t> genre,
        boost::optional<utility::string_t> players
    ) const;
    /// <summary>
    /// Download game file
    /// </summary>
    /// <remarks>
    /// Download the ROM or game file
    /// </remarks>
    /// <param name="id">Game ID</param>
    pplx::task<std::shared_ptr<HttpContent>> gamesIdFileGet(
        utility::string_t id
    ) const;
    /// <summary>
    /// Get a game by ID
    /// </summary>
    /// <remarks>
    /// Get a game by ID
    /// </remarks>
    /// <param name="id">Game ID</param>
    pplx::task<std::shared_ptr<Models_Game>> gamesIdGet(
        utility::string_t id
    ) const;
    /// <summary>
    /// Get a game image by ID
    /// </summary>
    /// <remarks>
    /// Get a game image by ID
    /// </remarks>
    /// <param name="id">Game ID</param>
    pplx::task<std::shared_ptr<HttpContent>> gamesIdImageGet(
        utility::string_t id
    ) const;
    /// <summary>
    /// Get a game marquee by ID
    /// </summary>
    /// <remarks>
    /// Get a game marquee by ID
    /// </remarks>
    /// <param name="id">Game ID</param>
    pplx::task<std::shared_ptr<HttpContent>> gamesIdMarqueeGet(
        utility::string_t id
    ) const;
    /// <summary>
    /// Download game patch
    /// </summary>
    /// <remarks>
    /// Download the game patch/save file
    /// </remarks>
    /// <param name="id">Game ID</param>
    pplx::task<std::shared_ptr<HttpContent>> gamesIdPatchGet(
        utility::string_t id
    ) const;
    /// <summary>
    /// Record a game play
    /// </summary>
    /// <remarks>
    /// Record that a game has been played. Optionally links to user profile if authenticated.
    /// </remarks>
    /// <param name="id">Game ID</param>
    /// <param name="authorization">Bearer token (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::map<utility::string_t, std::shared_ptr<AnyType>>> gamesIdPlayPost(
        utility::string_t id,
        boost::optional<utility::string_t> authorization
    ) const;
    /// <summary>
    /// Get a game thumbnail by ID
    /// </summary>
    /// <remarks>
    /// Get a game thumbnail by ID
    /// </remarks>
    /// <param name="id">Game ID</param>
    pplx::task<std::shared_ptr<HttpContent>> gamesIdThumbnailGet(
        utility::string_t id
    ) const;
    /// <summary>
    /// Get a game video by ID
    /// </summary>
    /// <remarks>
    /// Stream a game video by ID
    /// </remarks>
    /// <param name="id">Game ID</param>
    pplx::task<std::shared_ptr<HttpContent>> gamesIdVideoGet(
        utility::string_t id
    ) const;
    /// <summary>
    /// Import games
    /// </summary>
    /// <remarks>
    /// Import games from an EmulationStation gamelist.xml file
    /// </remarks>
    /// <param name="path">Path to gamelist.xml or directory containing it</param>
    pplx::task<std::map<utility::string_t, std::shared_ptr<AnyType>>> gamesImportPost(
        std::shared_ptr<Routes_ImportGamesRequest> path
    ) const;
    /// <summary>
    /// Get 5 random games (Am I Feeling Lucky?)
    /// </summary>
    /// <remarks>
    /// Returns 5 random games to discover new titles. Includes HowLongToBeat metadata if available.
    /// </remarks>
    pplx::task<std::vector<std::shared_ptr<Models_Game>>> gamesLuckyGet(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_GamesApi_H_ */

