/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MoviesApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_MoviesApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_MoviesApi_H_



#include "danflix_client/ApiClient.h"

#include "danflix_client/HttpContent.h"
#include "danflix_client/model/Models_Movie.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  MoviesApi 
{
public:

    explicit MoviesApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~MoviesApi();

    /// <summary>
    /// Get all movies
    /// </summary>
    /// <remarks>
    /// Get all movies from the database
    /// </remarks>
    /// <param name="genre">Filter by genre (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="studio">Filter by studio (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="director">Filter by director (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="actor">Filter by actor (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="producer">Filter by producer (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="decade">Filter by decade (e.g., 1990 for 1990s) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="includes">Comma separated list of relations to include (genres, studios, directors, actors, producers, languages, collections) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page">Page number (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="perPage">Items per page (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sort">Sort field (title, year, rating, runtime) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="order">Sort order (asc, desc) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::vector<std::shared_ptr<Models_Movie>>> moviesGet(
        boost::optional<utility::string_t> genre,
        boost::optional<utility::string_t> studio,
        boost::optional<utility::string_t> director,
        boost::optional<utility::string_t> actor,
        boost::optional<utility::string_t> producer,
        boost::optional<utility::string_t> decade,
        boost::optional<utility::string_t> includes,
        boost::optional<utility::string_t> page,
        boost::optional<utility::string_t> perPage,
        boost::optional<utility::string_t> sort,
        boost::optional<utility::string_t> order
    ) const;
    /// <summary>
    /// Get a movie banner
    /// </summary>
    /// <remarks>
    /// Get a movie banner from the database
    /// </remarks>
    /// <param name="id">Movie ID</param>
    pplx::task<std::shared_ptr<HttpContent>> moviesIdBannerGet(
        utility::string_t id
    ) const;
    /// <summary>
    /// Get a single movie
    /// </summary>
    /// <remarks>
    /// Get a single movie from the database
    /// </remarks>
    /// <param name="id">Movie ID</param>
    pplx::task<std::shared_ptr<Models_Movie>> moviesIdGet(
        utility::string_t id
    ) const;
    /// <summary>
    /// Get a movie poster
    /// </summary>
    /// <remarks>
    /// Get a movie poster from the database
    /// </remarks>
    /// <param name="id">Movie ID</param>
    pplx::task<std::shared_ptr<HttpContent>> moviesIdPosterGet(
        utility::string_t id
    ) const;
    /// <summary>
    /// Stream a movie
    /// </summary>
    /// <remarks>
    /// Stream a movie from the database
    /// </remarks>
    /// <param name="id">Movie ID</param>
    pplx::task<std::shared_ptr<HttpContent>> moviesIdStreamGet(
        utility::string_t id
    ) const;
    /// <summary>
    /// Get a movie subtitle
    /// </summary>
    /// <remarks>
    /// Get a movie subtitle from the database
    /// </remarks>
    /// <param name="id">Movie ID</param>
    pplx::task<std::shared_ptr<HttpContent>> moviesIdSubtitleGet(
        utility::string_t id
    ) const;
    /// <summary>
    /// Stream a movie trailer
    /// </summary>
    /// <remarks>
    /// Stream a movie trailer from the database
    /// </remarks>
    /// <param name="id">Movie ID</param>
    pplx::task<std::shared_ptr<HttpContent>> moviesIdTrailerGet(
        utility::string_t id
    ) const;
    /// <summary>
    /// Get 5 random movies
    /// </summary>
    /// <remarks>
    /// Returns 5 random movies.
    /// </remarks>
    pplx::task<std::vector<std::shared_ptr<Models_Movie>>> moviesLuckyGet(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_MoviesApi_H_ */

