/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ProgressApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_ProgressApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_ProgressApi_H_



#include "danflix_client/ApiClient.h"

#include "danflix_client/model/Models_MediaProgress.h"
#include "danflix_client/model/Routes_ProgressRequest.h"
#include <map>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ProgressApi 
{
public:

    explicit ProgressApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ProgressApi();

    /// <summary>
    /// Upsert progress
    /// </summary>
    /// <remarks>
    /// Create or update progress for any media type
    /// </remarks>
    /// <param name="progress">Progress data</param>
    pplx::task<std::map<utility::string_t, utility::string_t>> progressPut(
        std::shared_ptr<Routes_ProgressRequest> progress
    ) const;
    /// <summary>
    /// Get progress
    /// </summary>
    /// <remarks>
    /// Get progress for a specific media item
    /// </remarks>
    /// <param name="type">Media Type (movie, episode, game, tv)</param>
    /// <param name="id">Media ID</param>
    pplx::task<std::shared_ptr<Models_MediaProgress>> progressTypeIdGet(
        utility::string_t type,
        int32_t id
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_ProgressApi_H_ */

