/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SearchApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_SearchApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_SearchApi_H_



#include "danflix_client/ApiClient.h"
#include "danflix_client/ModelBase.h"
#include "danflix_client/AnyType.h"
#include <map>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  SearchApi 
{
public:

    explicit SearchApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~SearchApi();

    /// <summary>
    /// Search content
    /// </summary>
    /// <remarks>
    /// Search movies and shows by title
    /// </remarks>
    /// <param name="q">Search query</param>
    pplx::task<std::map<utility::string_t, std::shared_ptr<AnyType>>> searchGet(
        utility::string_t q
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_SearchApi_H_ */

