/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * StatusApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_StatusApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_StatusApi_H_



#include "danflix_client/ApiClient.h"
#include "danflix_client/ModelBase.h"
#include "danflix_client/AnyType.h"
#include <map>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  StatusApi 
{
public:

    explicit StatusApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~StatusApi();

    /// <summary>
    /// Set server status
    /// </summary>
    /// <remarks>
    /// Set globally if the server should force clients to pause.
    /// </remarks>
    /// <param name="status">Status object</param>
    pplx::task<std::map<utility::string_t, std::shared_ptr<AnyType>>> adminStatusPost(
        std::map<utility::string_t, bool> status
    ) const;
    /// <summary>
    /// Get server status
    /// </summary>
    /// <remarks>
    /// usage: Client polls this. If paused&#x3D;true, client forces pause.
    /// </remarks>
    pplx::task<std::map<utility::string_t, std::shared_ptr<AnyType>>> statusGet(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_StatusApi_H_ */

