/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TvApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_TvApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_TvApi_H_



#include "danflix_client/ApiClient.h"

#include "danflix_client/HttpContent.h"
#include "danflix_client/model/Models_Episode.h"
#include "danflix_client/model/Models_TVShow.h"
#include <map>
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  TvApi 
{
public:

    explicit TvApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~TvApi();

    /// <summary>
    /// Get TV shows
    /// </summary>
    /// <remarks>
    /// Get TV shows from the database
    /// </remarks>
    /// <param name="genre">Filter by genre (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="studio">Filter by studio (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="actor">Filter by actor (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="decade">Filter by decade (e.g., 1990 for 1990s) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::vector<std::shared_ptr<Models_TVShow>>> tvGet(
        boost::optional<utility::string_t> genre,
        boost::optional<utility::string_t> studio,
        boost::optional<utility::string_t> actor,
        boost::optional<utility::string_t> decade
    ) const;
    /// <summary>
    /// Get TV show banner
    /// </summary>
    /// <remarks>
    /// Get TV show banner from the database
    /// </remarks>
    /// <param name="id">TV show ID</param>
    pplx::task<std::shared_ptr<HttpContent>> tvIdBannerGet(
        int32_t id
    ) const;
    /// <summary>
    /// Get TV show
    /// </summary>
    /// <remarks>
    /// Get TV show from the database
    /// </remarks>
    /// <param name="id">TV show ID</param>
    pplx::task<std::shared_ptr<Models_TVShow>> tvIdGet(
        int32_t id
    ) const;
    /// <summary>
    /// Get next episode
    /// </summary>
    /// <remarks>
    /// Get next episode from the database
    /// </remarks>
    /// <param name="id">TV show ID</param>
    pplx::task<std::shared_ptr<Models_Episode>> tvIdNextGet(
        int32_t id
    ) const;
    /// <summary>
    /// Get TV show poster
    /// </summary>
    /// <remarks>
    /// Get TV show poster from the database
    /// </remarks>
    /// <param name="id">TV show ID</param>
    pplx::task<std::shared_ptr<HttpContent>> tvIdPosterGet(
        int32_t id
    ) const;
    /// <summary>
    /// Get episode
    /// </summary>
    /// <remarks>
    /// Get episode from the database
    /// </remarks>
    /// <param name="id">TV show ID</param>
    /// <param name="season">Season number</param>
    /// <param name="episode">Episode number</param>
    pplx::task<std::shared_ptr<Models_Episode>> tvIdSeasonsSeasonEpisodesEpisodeGet(
        int32_t id,
        int32_t season,
        int32_t episode
    ) const;
    /// <summary>
    /// Get episode poster
    /// </summary>
    /// <remarks>
    /// Get episode poster from the database
    /// </remarks>
    /// <param name="id">TV show ID</param>
    /// <param name="season">Season number</param>
    /// <param name="episode">Episode number</param>
    pplx::task<std::shared_ptr<HttpContent>> tvIdSeasonsSeasonEpisodesEpisodePosterGet(
        int32_t id,
        int32_t season,
        int32_t episode
    ) const;
    /// <summary>
    /// Stream episode
    /// </summary>
    /// <remarks>
    /// Stream episode from the database
    /// </remarks>
    /// <param name="id">TV show ID</param>
    /// <param name="season">Season number</param>
    /// <param name="episode">Episode number</param>
    pplx::task<std::shared_ptr<HttpContent>> tvIdSeasonsSeasonEpisodesEpisodeStreamGet(
        int32_t id,
        int32_t season,
        int32_t episode
    ) const;
    /// <summary>
    /// Get episode subtitle
    /// </summary>
    /// <remarks>
    /// Get episode subtitle from the database
    /// </remarks>
    /// <param name="id">TV show ID</param>
    /// <param name="season">Season number</param>
    /// <param name="episode">Episode number</param>
    pplx::task<std::shared_ptr<Models_Episode>> tvIdSeasonsSeasonEpisodesEpisodeSubtitleGet(
        int32_t id,
        int32_t season,
        int32_t episode
    ) const;
    /// <summary>
    /// Get season episodes
    /// </summary>
    /// <remarks>
    /// Get season episodes from the database
    /// </remarks>
    /// <param name="id">TV show ID</param>
    /// <param name="season">Season number</param>
    pplx::task<std::vector<std::shared_ptr<Models_Episode>>> tvIdSeasonsSeasonEpisodesGet(
        int32_t id,
        int32_t season
    ) const;
    /// <summary>
    /// Get TV show trailer
    /// </summary>
    /// <remarks>
    /// Get TV show trailer from the database
    /// </remarks>
    /// <param name="id">TV show ID</param>
    pplx::task<void> tvIdTrailerGet(
        int32_t id
    ) const;
    /// <summary>
    /// Get 5 random TV shows
    /// </summary>
    /// <remarks>
    /// Returns 5 random TV shows.
    /// </remarks>
    pplx::task<std::vector<std::shared_ptr<Models_TVShow>>> tvLuckyGet(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_TvApi_H_ */

