/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Gorm_DeletedAt.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Gorm_DeletedAt::Gorm_DeletedAt()
{
    m_Time = utility::conversions::to_string_t("");
    m_TimeIsSet = false;
    m_Valid = false;
    m_ValidIsSet = false;
}

Gorm_DeletedAt::~Gorm_DeletedAt()
{
}

void Gorm_DeletedAt::validate()
{
    // TODO: implement validation
}

web::json::value Gorm_DeletedAt::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_TimeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("time"))] = ModelBase::toJson(m_Time);
    }
    if(m_ValidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("valid"))] = ModelBase::toJson(m_Valid);
    }

    return val;
}

bool Gorm_DeletedAt::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("time"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("time")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTime;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTime);
            setTime(refVal_setTime);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("valid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("valid")));
        if(!fieldValue.is_null())
        {
            bool refVal_setValid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValid);
            setValid(refVal_setValid);
            
        }
    }
    return ok;
}

void Gorm_DeletedAt::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_TimeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("time")), m_Time));
    }
    if(m_ValidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("valid")), m_Valid));
    }
}

bool Gorm_DeletedAt::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("time"))))
    {
        utility::string_t refVal_setTime;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("time"))), refVal_setTime );
        setTime(refVal_setTime);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("valid"))))
    {
        bool refVal_setValid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("valid"))), refVal_setValid );
        setValid(refVal_setValid);
    }
    return ok;
}


utility::string_t Gorm_DeletedAt::getTime() const
{
    return m_Time;
}


void Gorm_DeletedAt::setTime(const utility::string_t& value)
{
    m_Time = value;
    m_TimeIsSet = true;
}

bool Gorm_DeletedAt::timeIsSet() const
{
    return m_TimeIsSet;
}

void Gorm_DeletedAt::unsetTime()
{
    m_TimeIsSet = false;
}
bool Gorm_DeletedAt::isValid() const
{
    return m_Valid;
}

void Gorm_DeletedAt::setValid(bool value)
{
    m_Valid = value;
    m_ValidIsSet = true;
}

bool Gorm_DeletedAt::validIsSet() const
{
    return m_ValidIsSet;
}

void Gorm_DeletedAt::unsetValid()
{
    m_ValidIsSet = false;
}

}
}
}
}


