/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Models_Play.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Models_Play::Models_Play()
{
    m_Client_ip = utility::conversions::to_string_t("");
    m_Client_ipIsSet = false;
    m_GameIsSet = false;
    m_Game_id = 0;
    m_Game_idIsSet = false;
    m_Id = 0;
    m_IdIsSet = false;
    m_Played_at = utility::conversions::to_string_t("");
    m_Played_atIsSet = false;
    m_Profile_id = 0;
    m_Profile_idIsSet = false;
}

Models_Play::~Models_Play()
{
}

void Models_Play::validate()
{
    // TODO: implement validation
}

web::json::value Models_Play::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Client_ipIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("client_ip"))] = ModelBase::toJson(m_Client_ip);
    }
    if(m_GameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("game"))] = ModelBase::toJson(m_Game);
    }
    if(m_Game_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("game_id"))] = ModelBase::toJson(m_Game_id);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_Played_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("played_at"))] = ModelBase::toJson(m_Played_at);
    }
    if(m_Profile_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("profile_id"))] = ModelBase::toJson(m_Profile_id);
    }

    return val;
}

bool Models_Play::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("client_ip"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("client_ip")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setClientIp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setClientIp);
            setClientIp(refVal_setClientIp);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("game"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("game")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Models_Game> refVal_setGame;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGame);
            setGame(refVal_setGame);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("game_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("game_id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setGameId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGameId);
            setGameId(refVal_setGameId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("played_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("played_at")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPlayedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPlayedAt);
            setPlayedAt(refVal_setPlayedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("profile_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("profile_id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setProfileId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProfileId);
            setProfileId(refVal_setProfileId);
            
        }
    }
    return ok;
}

void Models_Play::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Client_ipIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("client_ip")), m_Client_ip));
    }
    if(m_GameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("game")), m_Game));
    }
    if(m_Game_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("game_id")), m_Game_id));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_Played_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("played_at")), m_Played_at));
    }
    if(m_Profile_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("profile_id")), m_Profile_id));
    }
}

bool Models_Play::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("client_ip"))))
    {
        utility::string_t refVal_setClientIp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("client_ip"))), refVal_setClientIp );
        setClientIp(refVal_setClientIp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("game"))))
    {
        std::shared_ptr<Models_Game> refVal_setGame;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("game"))), refVal_setGame );
        setGame(refVal_setGame);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("game_id"))))
    {
        int32_t refVal_setGameId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("game_id"))), refVal_setGameId );
        setGameId(refVal_setGameId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("played_at"))))
    {
        utility::string_t refVal_setPlayedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("played_at"))), refVal_setPlayedAt );
        setPlayedAt(refVal_setPlayedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("profile_id"))))
    {
        int32_t refVal_setProfileId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("profile_id"))), refVal_setProfileId );
        setProfileId(refVal_setProfileId);
    }
    return ok;
}


utility::string_t Models_Play::getClientIp() const
{
    return m_Client_ip;
}


void Models_Play::setClientIp(const utility::string_t& value)
{
    m_Client_ip = value;
    m_Client_ipIsSet = true;
}

bool Models_Play::clientIpIsSet() const
{
    return m_Client_ipIsSet;
}

void Models_Play::unsetClient_ip()
{
    m_Client_ipIsSet = false;
}
std::shared_ptr<Models_Game> Models_Play::getGame() const
{
    return m_Game;
}


void Models_Play::setGame(const std::shared_ptr<Models_Game>& value)
{
    m_Game = value;
    m_GameIsSet = true;
}

bool Models_Play::gameIsSet() const
{
    return m_GameIsSet;
}

void Models_Play::unsetGame()
{
    m_GameIsSet = false;
}
int32_t Models_Play::getGameId() const
{
    return m_Game_id;
}

void Models_Play::setGameId(int32_t value)
{
    m_Game_id = value;
    m_Game_idIsSet = true;
}

bool Models_Play::gameIdIsSet() const
{
    return m_Game_idIsSet;
}

void Models_Play::unsetGame_id()
{
    m_Game_idIsSet = false;
}
int32_t Models_Play::getId() const
{
    return m_Id;
}

void Models_Play::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Models_Play::idIsSet() const
{
    return m_IdIsSet;
}

void Models_Play::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t Models_Play::getPlayedAt() const
{
    return m_Played_at;
}


void Models_Play::setPlayedAt(const utility::string_t& value)
{
    m_Played_at = value;
    m_Played_atIsSet = true;
}

bool Models_Play::playedAtIsSet() const
{
    return m_Played_atIsSet;
}

void Models_Play::unsetPlayed_at()
{
    m_Played_atIsSet = false;
}
int32_t Models_Play::getProfileId() const
{
    return m_Profile_id;
}

void Models_Play::setProfileId(int32_t value)
{
    m_Profile_id = value;
    m_Profile_idIsSet = true;
}

bool Models_Play::profileIdIsSet() const
{
    return m_Profile_idIsSet;
}

void Models_Play::unsetProfile_id()
{
    m_Profile_idIsSet = false;
}

}
}
}
}


