/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Models_Genre.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Models_Genre::Models_Genre()
{
    m_GamesIsSet = false;
    m_Id = 0;
    m_IdIsSet = false;
    m_MoviesIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_TvShowsIsSet = false;
}

Models_Genre::~Models_Genre()
{
}

void Models_Genre::validate()
{
    // TODO: implement validation
}

web::json::value Models_Genre::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_GamesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("games"))] = ModelBase::toJson(m_Games);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_MoviesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("movies"))] = ModelBase::toJson(m_Movies);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_TvShowsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tvShows"))] = ModelBase::toJson(m_TvShows);
    }

    return val;
}

bool Models_Genre::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("games"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("games")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_Game>> refVal_setGames;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGames);
            setGames(refVal_setGames);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("movies"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("movies")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_Movie>> refVal_setMovies;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMovies);
            setMovies(refVal_setMovies);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tvShows"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tvShows")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_TVShow>> refVal_setTvShows;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTvShows);
            setTvShows(refVal_setTvShows);
            
        }
    }
    return ok;
}

void Models_Genre::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_GamesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("games")), m_Games));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_MoviesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("movies")), m_Movies));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_TvShowsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tvShows")), m_TvShows));
    }
}

bool Models_Genre::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("games"))))
    {
        std::vector<std::shared_ptr<Models_Game>> refVal_setGames;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("games"))), refVal_setGames );
        setGames(refVal_setGames);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("movies"))))
    {
        std::vector<std::shared_ptr<Models_Movie>> refVal_setMovies;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("movies"))), refVal_setMovies );
        setMovies(refVal_setMovies);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tvShows"))))
    {
        std::vector<std::shared_ptr<Models_TVShow>> refVal_setTvShows;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tvShows"))), refVal_setTvShows );
        setTvShows(refVal_setTvShows);
    }
    return ok;
}


std::vector<std::shared_ptr<Models_Game>> Models_Genre::getGames() const
{
    return m_Games;
}


void Models_Genre::setGames(const std::vector<std::shared_ptr<Models_Game>>& value)
{
    m_Games = value;
    m_GamesIsSet = true;
}

bool Models_Genre::gamesIsSet() const
{
    return m_GamesIsSet;
}

void Models_Genre::unsetGames()
{
    m_GamesIsSet = false;
}
int32_t Models_Genre::getId() const
{
    return m_Id;
}

void Models_Genre::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Models_Genre::idIsSet() const
{
    return m_IdIsSet;
}

void Models_Genre::unsetId()
{
    m_IdIsSet = false;
}
std::vector<std::shared_ptr<Models_Movie>> Models_Genre::getMovies() const
{
    return m_Movies;
}


void Models_Genre::setMovies(const std::vector<std::shared_ptr<Models_Movie>>& value)
{
    m_Movies = value;
    m_MoviesIsSet = true;
}

bool Models_Genre::moviesIsSet() const
{
    return m_MoviesIsSet;
}

void Models_Genre::unsetMovies()
{
    m_MoviesIsSet = false;
}
utility::string_t Models_Genre::getName() const
{
    return m_Name;
}


void Models_Genre::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Models_Genre::nameIsSet() const
{
    return m_NameIsSet;
}

void Models_Genre::unsetName()
{
    m_NameIsSet = false;
}
std::vector<std::shared_ptr<Models_TVShow>> Models_Genre::getTvShows() const
{
    return m_TvShows;
}


void Models_Genre::setTvShows(const std::vector<std::shared_ptr<Models_TVShow>>& value)
{
    m_TvShows = value;
    m_TvShowsIsSet = true;
}

bool Models_Genre::tvShowsIsSet() const
{
    return m_TvShowsIsSet;
}

void Models_Genre::unsetTvShows()
{
    m_TvShowsIsSet = false;
}

}
}
}
}


