/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Models_MediaProgress.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Models_MediaProgress::Models_MediaProgress()
{
    m_CreatedAt = utility::conversions::to_string_t("");
    m_CreatedAtIsSet = false;
    m_DeletedAtIsSet = false;
    m_EpisodeIsSet = false;
    m_Finished = false;
    m_FinishedIsSet = false;
    m_Id = 0;
    m_IdIsSet = false;
    m_MediaId = 0;
    m_MediaIdIsSet = false;
    m_MediaType = utility::conversions::to_string_t("");
    m_MediaTypeIsSet = false;
    m_MovieIsSet = false;
    m_ProfileId = 0;
    m_ProfileIdIsSet = false;
    m_Progress = 0;
    m_ProgressIsSet = false;
    m_Total = 0;
    m_TotalIsSet = false;
    m_UpdatedAt = utility::conversions::to_string_t("");
    m_UpdatedAtIsSet = false;
}

Models_MediaProgress::~Models_MediaProgress()
{
}

void Models_MediaProgress::validate()
{
    // TODO: implement validation
}

web::json::value Models_MediaProgress::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CreatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }
    if(m_DeletedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("deletedAt"))] = ModelBase::toJson(m_DeletedAt);
    }
    if(m_EpisodeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("episode"))] = ModelBase::toJson(m_Episode);
    }
    if(m_FinishedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("finished"))] = ModelBase::toJson(m_Finished);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_MediaIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("mediaId"))] = ModelBase::toJson(m_MediaId);
    }
    if(m_MediaTypeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("mediaType"))] = ModelBase::toJson(m_MediaType);
    }
    if(m_MovieIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("movie"))] = ModelBase::toJson(m_Movie);
    }
    if(m_ProfileIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("profileId"))] = ModelBase::toJson(m_ProfileId);
    }
    if(m_ProgressIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("progress"))] = ModelBase::toJson(m_Progress);
    }
    if(m_TotalIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("total"))] = ModelBase::toJson(m_Total);
    }
    if(m_UpdatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updatedAt"))] = ModelBase::toJson(m_UpdatedAt);
    }

    return val;
}

bool Models_MediaProgress::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("deletedAt")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Gorm_DeletedAt> refVal_setDeletedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeletedAt);
            setDeletedAt(refVal_setDeletedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("episode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("episode")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Models_Episode> refVal_setEpisode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEpisode);
            setEpisode(refVal_setEpisode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("finished"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("finished")));
        if(!fieldValue.is_null())
        {
            bool refVal_setFinished;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFinished);
            setFinished(refVal_setFinished);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("mediaId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("mediaId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setMediaId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMediaId);
            setMediaId(refVal_setMediaId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("mediaType"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("mediaType")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMediaType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMediaType);
            setMediaType(refVal_setMediaType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("movie"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("movie")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Models_Movie> refVal_setMovie;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMovie);
            setMovie(refVal_setMovie);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("profileId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("profileId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setProfileId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProfileId);
            setProfileId(refVal_setProfileId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("progress"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("progress")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setProgress;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProgress);
            setProgress(refVal_setProgress);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("total"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("total")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotal;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotal);
            setTotal(refVal_setTotal);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updatedAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    return ok;
}

void Models_MediaProgress::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
    if(m_DeletedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("deletedAt")), m_DeletedAt));
    }
    if(m_EpisodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("episode")), m_Episode));
    }
    if(m_FinishedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("finished")), m_Finished));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_MediaIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("mediaId")), m_MediaId));
    }
    if(m_MediaTypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("mediaType")), m_MediaType));
    }
    if(m_MovieIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("movie")), m_Movie));
    }
    if(m_ProfileIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("profileId")), m_ProfileId));
    }
    if(m_ProgressIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("progress")), m_Progress));
    }
    if(m_TotalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("total")), m_Total));
    }
    if(m_UpdatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updatedAt")), m_UpdatedAt));
    }
}

bool Models_MediaProgress::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::string_t refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))))
    {
        std::shared_ptr<Gorm_DeletedAt> refVal_setDeletedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))), refVal_setDeletedAt );
        setDeletedAt(refVal_setDeletedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("episode"))))
    {
        std::shared_ptr<Models_Episode> refVal_setEpisode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("episode"))), refVal_setEpisode );
        setEpisode(refVal_setEpisode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("finished"))))
    {
        bool refVal_setFinished;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("finished"))), refVal_setFinished );
        setFinished(refVal_setFinished);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("mediaId"))))
    {
        int32_t refVal_setMediaId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("mediaId"))), refVal_setMediaId );
        setMediaId(refVal_setMediaId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("mediaType"))))
    {
        utility::string_t refVal_setMediaType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("mediaType"))), refVal_setMediaType );
        setMediaType(refVal_setMediaType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("movie"))))
    {
        std::shared_ptr<Models_Movie> refVal_setMovie;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("movie"))), refVal_setMovie );
        setMovie(refVal_setMovie);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("profileId"))))
    {
        int32_t refVal_setProfileId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("profileId"))), refVal_setProfileId );
        setProfileId(refVal_setProfileId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("progress"))))
    {
        int32_t refVal_setProgress;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("progress"))), refVal_setProgress );
        setProgress(refVal_setProgress);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("total"))))
    {
        int32_t refVal_setTotal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("total"))), refVal_setTotal );
        setTotal(refVal_setTotal);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        utility::string_t refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    return ok;
}


utility::string_t Models_MediaProgress::getCreatedAt() const
{
    return m_CreatedAt;
}


void Models_MediaProgress::setCreatedAt(const utility::string_t& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool Models_MediaProgress::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void Models_MediaProgress::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}
std::shared_ptr<Gorm_DeletedAt> Models_MediaProgress::getDeletedAt() const
{
    return m_DeletedAt;
}


void Models_MediaProgress::setDeletedAt(const std::shared_ptr<Gorm_DeletedAt>& value)
{
    m_DeletedAt = value;
    m_DeletedAtIsSet = true;
}

bool Models_MediaProgress::deletedAtIsSet() const
{
    return m_DeletedAtIsSet;
}

void Models_MediaProgress::unsetDeletedAt()
{
    m_DeletedAtIsSet = false;
}
std::shared_ptr<Models_Episode> Models_MediaProgress::getEpisode() const
{
    return m_Episode;
}


void Models_MediaProgress::setEpisode(const std::shared_ptr<Models_Episode>& value)
{
    m_Episode = value;
    m_EpisodeIsSet = true;
}

bool Models_MediaProgress::episodeIsSet() const
{
    return m_EpisodeIsSet;
}

void Models_MediaProgress::unsetEpisode()
{
    m_EpisodeIsSet = false;
}
bool Models_MediaProgress::isFinished() const
{
    return m_Finished;
}

void Models_MediaProgress::setFinished(bool value)
{
    m_Finished = value;
    m_FinishedIsSet = true;
}

bool Models_MediaProgress::finishedIsSet() const
{
    return m_FinishedIsSet;
}

void Models_MediaProgress::unsetFinished()
{
    m_FinishedIsSet = false;
}
int32_t Models_MediaProgress::getId() const
{
    return m_Id;
}

void Models_MediaProgress::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Models_MediaProgress::idIsSet() const
{
    return m_IdIsSet;
}

void Models_MediaProgress::unsetId()
{
    m_IdIsSet = false;
}
int32_t Models_MediaProgress::getMediaId() const
{
    return m_MediaId;
}

void Models_MediaProgress::setMediaId(int32_t value)
{
    m_MediaId = value;
    m_MediaIdIsSet = true;
}

bool Models_MediaProgress::mediaIdIsSet() const
{
    return m_MediaIdIsSet;
}

void Models_MediaProgress::unsetMediaId()
{
    m_MediaIdIsSet = false;
}
utility::string_t Models_MediaProgress::getMediaType() const
{
    return m_MediaType;
}


void Models_MediaProgress::setMediaType(const utility::string_t& value)
{
    m_MediaType = value;
    m_MediaTypeIsSet = true;
}

bool Models_MediaProgress::mediaTypeIsSet() const
{
    return m_MediaTypeIsSet;
}

void Models_MediaProgress::unsetMediaType()
{
    m_MediaTypeIsSet = false;
}
std::shared_ptr<Models_Movie> Models_MediaProgress::getMovie() const
{
    return m_Movie;
}


void Models_MediaProgress::setMovie(const std::shared_ptr<Models_Movie>& value)
{
    m_Movie = value;
    m_MovieIsSet = true;
}

bool Models_MediaProgress::movieIsSet() const
{
    return m_MovieIsSet;
}

void Models_MediaProgress::unsetMovie()
{
    m_MovieIsSet = false;
}
int32_t Models_MediaProgress::getProfileId() const
{
    return m_ProfileId;
}

void Models_MediaProgress::setProfileId(int32_t value)
{
    m_ProfileId = value;
    m_ProfileIdIsSet = true;
}

bool Models_MediaProgress::profileIdIsSet() const
{
    return m_ProfileIdIsSet;
}

void Models_MediaProgress::unsetProfileId()
{
    m_ProfileIdIsSet = false;
}
int32_t Models_MediaProgress::getProgress() const
{
    return m_Progress;
}

void Models_MediaProgress::setProgress(int32_t value)
{
    m_Progress = value;
    m_ProgressIsSet = true;
}

bool Models_MediaProgress::progressIsSet() const
{
    return m_ProgressIsSet;
}

void Models_MediaProgress::unsetProgress()
{
    m_ProgressIsSet = false;
}
int32_t Models_MediaProgress::getTotal() const
{
    return m_Total;
}

void Models_MediaProgress::setTotal(int32_t value)
{
    m_Total = value;
    m_TotalIsSet = true;
}

bool Models_MediaProgress::totalIsSet() const
{
    return m_TotalIsSet;
}

void Models_MediaProgress::unsetTotal()
{
    m_TotalIsSet = false;
}
utility::string_t Models_MediaProgress::getUpdatedAt() const
{
    return m_UpdatedAt;
}


void Models_MediaProgress::setUpdatedAt(const utility::string_t& value)
{
    m_UpdatedAt = value;
    m_UpdatedAtIsSet = true;
}

bool Models_MediaProgress::updatedAtIsSet() const
{
    return m_UpdatedAtIsSet;
}

void Models_MediaProgress::unsetUpdatedAt()
{
    m_UpdatedAtIsSet = false;
}

}
}
}
}


