/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Models_Patch.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Models_Patch::Models_Patch()
{
    m_CreatedAt = utility::conversions::to_string_t("");
    m_CreatedAtIsSet = false;
    m_DeletedAtIsSet = false;
    m_GameId = 0;
    m_GameIdIsSet = false;
    m_Id = 0;
    m_IdIsSet = false;
    m_Path = utility::conversions::to_string_t("");
    m_PathIsSet = false;
    m_Title = utility::conversions::to_string_t("");
    m_TitleIsSet = false;
    m_UpdatedAt = utility::conversions::to_string_t("");
    m_UpdatedAtIsSet = false;
    m_Version = utility::conversions::to_string_t("");
    m_VersionIsSet = false;
}

Models_Patch::~Models_Patch()
{
}

void Models_Patch::validate()
{
    // TODO: implement validation
}

web::json::value Models_Patch::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CreatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }
    if(m_DeletedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("deletedAt"))] = ModelBase::toJson(m_DeletedAt);
    }
    if(m_GameIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("gameId"))] = ModelBase::toJson(m_GameId);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_PathIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("path"))] = ModelBase::toJson(m_Path);
    }
    if(m_TitleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("title"))] = ModelBase::toJson(m_Title);
    }
    if(m_UpdatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updatedAt"))] = ModelBase::toJson(m_UpdatedAt);
    }
    if(m_VersionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("version"))] = ModelBase::toJson(m_Version);
    }

    return val;
}

bool Models_Patch::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("deletedAt")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Gorm_DeletedAt> refVal_setDeletedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeletedAt);
            setDeletedAt(refVal_setDeletedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("gameId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("gameId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setGameId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGameId);
            setGameId(refVal_setGameId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("path"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("path")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPath;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPath);
            setPath(refVal_setPath);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitle);
            setTitle(refVal_setTitle);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updatedAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("version"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("version")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setVersion;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVersion);
            setVersion(refVal_setVersion);
            
        }
    }
    return ok;
}

void Models_Patch::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
    if(m_DeletedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("deletedAt")), m_DeletedAt));
    }
    if(m_GameIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("gameId")), m_GameId));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_PathIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("path")), m_Path));
    }
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("title")), m_Title));
    }
    if(m_UpdatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updatedAt")), m_UpdatedAt));
    }
    if(m_VersionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("version")), m_Version));
    }
}

bool Models_Patch::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::string_t refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))))
    {
        std::shared_ptr<Gorm_DeletedAt> refVal_setDeletedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))), refVal_setDeletedAt );
        setDeletedAt(refVal_setDeletedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("gameId"))))
    {
        int32_t refVal_setGameId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("gameId"))), refVal_setGameId );
        setGameId(refVal_setGameId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("path"))))
    {
        utility::string_t refVal_setPath;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("path"))), refVal_setPath );
        setPath(refVal_setPath);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        utility::string_t refVal_setTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("title"))), refVal_setTitle );
        setTitle(refVal_setTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        utility::string_t refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("version"))))
    {
        utility::string_t refVal_setVersion;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("version"))), refVal_setVersion );
        setVersion(refVal_setVersion);
    }
    return ok;
}


utility::string_t Models_Patch::getCreatedAt() const
{
    return m_CreatedAt;
}


void Models_Patch::setCreatedAt(const utility::string_t& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool Models_Patch::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void Models_Patch::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}
std::shared_ptr<Gorm_DeletedAt> Models_Patch::getDeletedAt() const
{
    return m_DeletedAt;
}


void Models_Patch::setDeletedAt(const std::shared_ptr<Gorm_DeletedAt>& value)
{
    m_DeletedAt = value;
    m_DeletedAtIsSet = true;
}

bool Models_Patch::deletedAtIsSet() const
{
    return m_DeletedAtIsSet;
}

void Models_Patch::unsetDeletedAt()
{
    m_DeletedAtIsSet = false;
}
int32_t Models_Patch::getGameId() const
{
    return m_GameId;
}

void Models_Patch::setGameId(int32_t value)
{
    m_GameId = value;
    m_GameIdIsSet = true;
}

bool Models_Patch::gameIdIsSet() const
{
    return m_GameIdIsSet;
}

void Models_Patch::unsetGameId()
{
    m_GameIdIsSet = false;
}
int32_t Models_Patch::getId() const
{
    return m_Id;
}

void Models_Patch::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Models_Patch::idIsSet() const
{
    return m_IdIsSet;
}

void Models_Patch::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t Models_Patch::getPath() const
{
    return m_Path;
}


void Models_Patch::setPath(const utility::string_t& value)
{
    m_Path = value;
    m_PathIsSet = true;
}

bool Models_Patch::pathIsSet() const
{
    return m_PathIsSet;
}

void Models_Patch::unsetPath()
{
    m_PathIsSet = false;
}
utility::string_t Models_Patch::getTitle() const
{
    return m_Title;
}


void Models_Patch::setTitle(const utility::string_t& value)
{
    m_Title = value;
    m_TitleIsSet = true;
}

bool Models_Patch::titleIsSet() const
{
    return m_TitleIsSet;
}

void Models_Patch::unsetTitle()
{
    m_TitleIsSet = false;
}
utility::string_t Models_Patch::getUpdatedAt() const
{
    return m_UpdatedAt;
}


void Models_Patch::setUpdatedAt(const utility::string_t& value)
{
    m_UpdatedAt = value;
    m_UpdatedAtIsSet = true;
}

bool Models_Patch::updatedAtIsSet() const
{
    return m_UpdatedAtIsSet;
}

void Models_Patch::unsetUpdatedAt()
{
    m_UpdatedAtIsSet = false;
}
utility::string_t Models_Patch::getVersion() const
{
    return m_Version;
}


void Models_Patch::setVersion(const utility::string_t& value)
{
    m_Version = value;
    m_VersionIsSet = true;
}

bool Models_Patch::versionIsSet() const
{
    return m_VersionIsSet;
}

void Models_Patch::unsetVersion()
{
    m_VersionIsSet = false;
}

}
}
}
}


