/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Models_Collection.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Models_Collection::Models_Collection()
{
    m_Backdrop = utility::conversions::to_string_t("");
    m_BackdropIsSet = false;
    m_CreatedAt = utility::conversions::to_string_t("");
    m_CreatedAtIsSet = false;
    m_DeletedAtIsSet = false;
    m_GamesIsSet = false;
    m_Id = 0;
    m_IdIsSet = false;
    m_MoviesIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Overview = utility::conversions::to_string_t("");
    m_OverviewIsSet = false;
    m_Poster = utility::conversions::to_string_t("");
    m_PosterIsSet = false;
    m_ShowsIsSet = false;
    m_UpdatedAt = utility::conversions::to_string_t("");
    m_UpdatedAtIsSet = false;
}

Models_Collection::~Models_Collection()
{
}

void Models_Collection::validate()
{
    // TODO: implement validation
}

web::json::value Models_Collection::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_BackdropIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("backdrop"))] = ModelBase::toJson(m_Backdrop);
    }
    if(m_CreatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }
    if(m_DeletedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("deletedAt"))] = ModelBase::toJson(m_DeletedAt);
    }
    if(m_GamesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("games"))] = ModelBase::toJson(m_Games);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_MoviesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("movies"))] = ModelBase::toJson(m_Movies);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_OverviewIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("overview"))] = ModelBase::toJson(m_Overview);
    }
    if(m_PosterIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("poster"))] = ModelBase::toJson(m_Poster);
    }
    if(m_ShowsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("shows"))] = ModelBase::toJson(m_Shows);
    }
    if(m_UpdatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updatedAt"))] = ModelBase::toJson(m_UpdatedAt);
    }

    return val;
}

bool Models_Collection::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("backdrop"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("backdrop")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBackdrop;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBackdrop);
            setBackdrop(refVal_setBackdrop);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("deletedAt")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Gorm_DeletedAt> refVal_setDeletedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeletedAt);
            setDeletedAt(refVal_setDeletedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("games"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("games")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_Game>> refVal_setGames;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGames);
            setGames(refVal_setGames);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("movies"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("movies")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_Movie>> refVal_setMovies;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMovies);
            setMovies(refVal_setMovies);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("overview"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("overview")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOverview;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOverview);
            setOverview(refVal_setOverview);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("poster"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("poster")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPoster;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPoster);
            setPoster(refVal_setPoster);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("shows"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("shows")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_TVShow>> refVal_setShows;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShows);
            setShows(refVal_setShows);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updatedAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    return ok;
}

void Models_Collection::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_BackdropIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("backdrop")), m_Backdrop));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
    if(m_DeletedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("deletedAt")), m_DeletedAt));
    }
    if(m_GamesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("games")), m_Games));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_MoviesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("movies")), m_Movies));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_OverviewIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("overview")), m_Overview));
    }
    if(m_PosterIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("poster")), m_Poster));
    }
    if(m_ShowsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("shows")), m_Shows));
    }
    if(m_UpdatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updatedAt")), m_UpdatedAt));
    }
}

bool Models_Collection::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("backdrop"))))
    {
        utility::string_t refVal_setBackdrop;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("backdrop"))), refVal_setBackdrop );
        setBackdrop(refVal_setBackdrop);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::string_t refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))))
    {
        std::shared_ptr<Gorm_DeletedAt> refVal_setDeletedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))), refVal_setDeletedAt );
        setDeletedAt(refVal_setDeletedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("games"))))
    {
        std::vector<std::shared_ptr<Models_Game>> refVal_setGames;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("games"))), refVal_setGames );
        setGames(refVal_setGames);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("movies"))))
    {
        std::vector<std::shared_ptr<Models_Movie>> refVal_setMovies;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("movies"))), refVal_setMovies );
        setMovies(refVal_setMovies);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("overview"))))
    {
        utility::string_t refVal_setOverview;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("overview"))), refVal_setOverview );
        setOverview(refVal_setOverview);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("poster"))))
    {
        utility::string_t refVal_setPoster;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("poster"))), refVal_setPoster );
        setPoster(refVal_setPoster);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("shows"))))
    {
        std::vector<std::shared_ptr<Models_TVShow>> refVal_setShows;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("shows"))), refVal_setShows );
        setShows(refVal_setShows);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        utility::string_t refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    return ok;
}


utility::string_t Models_Collection::getBackdrop() const
{
    return m_Backdrop;
}


void Models_Collection::setBackdrop(const utility::string_t& value)
{
    m_Backdrop = value;
    m_BackdropIsSet = true;
}

bool Models_Collection::backdropIsSet() const
{
    return m_BackdropIsSet;
}

void Models_Collection::unsetBackdrop()
{
    m_BackdropIsSet = false;
}
utility::string_t Models_Collection::getCreatedAt() const
{
    return m_CreatedAt;
}


void Models_Collection::setCreatedAt(const utility::string_t& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool Models_Collection::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void Models_Collection::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}
std::shared_ptr<Gorm_DeletedAt> Models_Collection::getDeletedAt() const
{
    return m_DeletedAt;
}


void Models_Collection::setDeletedAt(const std::shared_ptr<Gorm_DeletedAt>& value)
{
    m_DeletedAt = value;
    m_DeletedAtIsSet = true;
}

bool Models_Collection::deletedAtIsSet() const
{
    return m_DeletedAtIsSet;
}

void Models_Collection::unsetDeletedAt()
{
    m_DeletedAtIsSet = false;
}
std::vector<std::shared_ptr<Models_Game>> Models_Collection::getGames() const
{
    return m_Games;
}


void Models_Collection::setGames(const std::vector<std::shared_ptr<Models_Game>>& value)
{
    m_Games = value;
    m_GamesIsSet = true;
}

bool Models_Collection::gamesIsSet() const
{
    return m_GamesIsSet;
}

void Models_Collection::unsetGames()
{
    m_GamesIsSet = false;
}
int32_t Models_Collection::getId() const
{
    return m_Id;
}

void Models_Collection::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Models_Collection::idIsSet() const
{
    return m_IdIsSet;
}

void Models_Collection::unsetId()
{
    m_IdIsSet = false;
}
std::vector<std::shared_ptr<Models_Movie>> Models_Collection::getMovies() const
{
    return m_Movies;
}


void Models_Collection::setMovies(const std::vector<std::shared_ptr<Models_Movie>>& value)
{
    m_Movies = value;
    m_MoviesIsSet = true;
}

bool Models_Collection::moviesIsSet() const
{
    return m_MoviesIsSet;
}

void Models_Collection::unsetMovies()
{
    m_MoviesIsSet = false;
}
utility::string_t Models_Collection::getName() const
{
    return m_Name;
}


void Models_Collection::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Models_Collection::nameIsSet() const
{
    return m_NameIsSet;
}

void Models_Collection::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t Models_Collection::getOverview() const
{
    return m_Overview;
}


void Models_Collection::setOverview(const utility::string_t& value)
{
    m_Overview = value;
    m_OverviewIsSet = true;
}

bool Models_Collection::overviewIsSet() const
{
    return m_OverviewIsSet;
}

void Models_Collection::unsetOverview()
{
    m_OverviewIsSet = false;
}
utility::string_t Models_Collection::getPoster() const
{
    return m_Poster;
}


void Models_Collection::setPoster(const utility::string_t& value)
{
    m_Poster = value;
    m_PosterIsSet = true;
}

bool Models_Collection::posterIsSet() const
{
    return m_PosterIsSet;
}

void Models_Collection::unsetPoster()
{
    m_PosterIsSet = false;
}
std::vector<std::shared_ptr<Models_TVShow>> Models_Collection::getShows() const
{
    return m_Shows;
}


void Models_Collection::setShows(const std::vector<std::shared_ptr<Models_TVShow>>& value)
{
    m_Shows = value;
    m_ShowsIsSet = true;
}

bool Models_Collection::showsIsSet() const
{
    return m_ShowsIsSet;
}

void Models_Collection::unsetShows()
{
    m_ShowsIsSet = false;
}
utility::string_t Models_Collection::getUpdatedAt() const
{
    return m_UpdatedAt;
}


void Models_Collection::setUpdatedAt(const utility::string_t& value)
{
    m_UpdatedAt = value;
    m_UpdatedAtIsSet = true;
}

bool Models_Collection::updatedAtIsSet() const
{
    return m_UpdatedAtIsSet;
}

void Models_Collection::unsetUpdatedAt()
{
    m_UpdatedAtIsSet = false;
}

}
}
}
}


