/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Models_Client.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Models_Client::Models_Client()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Ip = utility::conversions::to_string_t("");
    m_IpIsSet = false;
    m_LastSeen = utility::conversions::to_string_t("");
    m_LastSeenIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_RegisteredAt = utility::conversions::to_string_t("");
    m_RegisteredAtIsSet = false;
    m_UserAgent = utility::conversions::to_string_t("");
    m_UserAgentIsSet = false;
}

Models_Client::~Models_Client()
{
}

void Models_Client::validate()
{
    // TODO: implement validation
}

web::json::value Models_Client::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_IpIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("ip"))] = ModelBase::toJson(m_Ip);
    }
    if(m_LastSeenIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("lastSeen"))] = ModelBase::toJson(m_LastSeen);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_RegisteredAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("registeredAt"))] = ModelBase::toJson(m_RegisteredAt);
    }
    if(m_UserAgentIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("userAgent"))] = ModelBase::toJson(m_UserAgent);
    }

    return val;
}

bool Models_Client::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("ip"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("ip")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setIp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIp);
            setIp(refVal_setIp);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("lastSeen"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("lastSeen")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLastSeen;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastSeen);
            setLastSeen(refVal_setLastSeen);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("registeredAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("registeredAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRegisteredAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRegisteredAt);
            setRegisteredAt(refVal_setRegisteredAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("userAgent"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("userAgent")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUserAgent;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUserAgent);
            setUserAgent(refVal_setUserAgent);
            
        }
    }
    return ok;
}

void Models_Client::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_IpIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("ip")), m_Ip));
    }
    if(m_LastSeenIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("lastSeen")), m_LastSeen));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_RegisteredAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("registeredAt")), m_RegisteredAt));
    }
    if(m_UserAgentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("userAgent")), m_UserAgent));
    }
}

bool Models_Client::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("ip"))))
    {
        utility::string_t refVal_setIp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("ip"))), refVal_setIp );
        setIp(refVal_setIp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("lastSeen"))))
    {
        utility::string_t refVal_setLastSeen;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("lastSeen"))), refVal_setLastSeen );
        setLastSeen(refVal_setLastSeen);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("registeredAt"))))
    {
        utility::string_t refVal_setRegisteredAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("registeredAt"))), refVal_setRegisteredAt );
        setRegisteredAt(refVal_setRegisteredAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("userAgent"))))
    {
        utility::string_t refVal_setUserAgent;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("userAgent"))), refVal_setUserAgent );
        setUserAgent(refVal_setUserAgent);
    }
    return ok;
}


utility::string_t Models_Client::getId() const
{
    return m_Id;
}


void Models_Client::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Models_Client::idIsSet() const
{
    return m_IdIsSet;
}

void Models_Client::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t Models_Client::getIp() const
{
    return m_Ip;
}


void Models_Client::setIp(const utility::string_t& value)
{
    m_Ip = value;
    m_IpIsSet = true;
}

bool Models_Client::ipIsSet() const
{
    return m_IpIsSet;
}

void Models_Client::unsetIp()
{
    m_IpIsSet = false;
}
utility::string_t Models_Client::getLastSeen() const
{
    return m_LastSeen;
}


void Models_Client::setLastSeen(const utility::string_t& value)
{
    m_LastSeen = value;
    m_LastSeenIsSet = true;
}

bool Models_Client::lastSeenIsSet() const
{
    return m_LastSeenIsSet;
}

void Models_Client::unsetLastSeen()
{
    m_LastSeenIsSet = false;
}
utility::string_t Models_Client::getName() const
{
    return m_Name;
}


void Models_Client::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Models_Client::nameIsSet() const
{
    return m_NameIsSet;
}

void Models_Client::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t Models_Client::getRegisteredAt() const
{
    return m_RegisteredAt;
}


void Models_Client::setRegisteredAt(const utility::string_t& value)
{
    m_RegisteredAt = value;
    m_RegisteredAtIsSet = true;
}

bool Models_Client::registeredAtIsSet() const
{
    return m_RegisteredAtIsSet;
}

void Models_Client::unsetRegisteredAt()
{
    m_RegisteredAtIsSet = false;
}
utility::string_t Models_Client::getUserAgent() const
{
    return m_UserAgent;
}


void Models_Client::setUserAgent(const utility::string_t& value)
{
    m_UserAgent = value;
    m_UserAgentIsSet = true;
}

bool Models_Client::userAgentIsSet() const
{
    return m_UserAgentIsSet;
}

void Models_Client::unsetUserAgent()
{
    m_UserAgentIsSet = false;
}

}
}
}
}


