/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Models_Episode.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Models_Episode::Models_Episode()
{
    m_ActorsIsSet = false;
    m_Banner = utility::conversions::to_string_t("");
    m_BannerIsSet = false;
    m_Certification = utility::conversions::to_string_t("");
    m_CertificationIsSet = false;
    m_CreatedAt = utility::conversions::to_string_t("");
    m_CreatedAtIsSet = false;
    m_DeletedAtIsSet = false;
    m_DirectorsIsSet = false;
    m_Episode = 0;
    m_EpisodeIsSet = false;
    m_Filepath = utility::conversions::to_string_t("");
    m_FilepathIsSet = false;
    m_GenresIsSet = false;
    m_Id = 0;
    m_IdIsSet = false;
    m_LanguagesIsSet = false;
    m_OriginalTitle = utility::conversions::to_string_t("");
    m_OriginalTitleIsSet = false;
    m_Plot = utility::conversions::to_string_t("");
    m_PlotIsSet = false;
    m_Poster = utility::conversions::to_string_t("");
    m_PosterIsSet = false;
    m_ProducersIsSet = false;
    m_Rating = 0.0;
    m_RatingIsSet = false;
    m_Runtime = 0;
    m_RuntimeIsSet = false;
    m_Season = 0;
    m_SeasonIsSet = false;
    m_StudiosIsSet = false;
    m_Tagline = utility::conversions::to_string_t("");
    m_TaglineIsSet = false;
    m_Title = utility::conversions::to_string_t("");
    m_TitleIsSet = false;
    m_Trailer = utility::conversions::to_string_t("");
    m_TrailerIsSet = false;
    m_TvShowIsSet = false;
    m_TvShowId = 0;
    m_TvShowIdIsSet = false;
    m_UpdatedAt = utility::conversions::to_string_t("");
    m_UpdatedAtIsSet = false;
    m_Year = 0;
    m_YearIsSet = false;
}

Models_Episode::~Models_Episode()
{
}

void Models_Episode::validate()
{
    // TODO: implement validation
}

web::json::value Models_Episode::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ActorsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("actors"))] = ModelBase::toJson(m_Actors);
    }
    if(m_BannerIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("banner"))] = ModelBase::toJson(m_Banner);
    }
    if(m_CertificationIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("certification"))] = ModelBase::toJson(m_Certification);
    }
    if(m_CreatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }
    if(m_DeletedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("deletedAt"))] = ModelBase::toJson(m_DeletedAt);
    }
    if(m_DirectorsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("directors"))] = ModelBase::toJson(m_Directors);
    }
    if(m_EpisodeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("episode"))] = ModelBase::toJson(m_Episode);
    }
    if(m_FilepathIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("filepath"))] = ModelBase::toJson(m_Filepath);
    }
    if(m_GenresIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("genres"))] = ModelBase::toJson(m_Genres);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_LanguagesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("languages"))] = ModelBase::toJson(m_Languages);
    }
    if(m_OriginalTitleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("originalTitle"))] = ModelBase::toJson(m_OriginalTitle);
    }
    if(m_PlotIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("plot"))] = ModelBase::toJson(m_Plot);
    }
    if(m_PosterIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("poster"))] = ModelBase::toJson(m_Poster);
    }
    if(m_ProducersIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("producers"))] = ModelBase::toJson(m_Producers);
    }
    if(m_RatingIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("rating"))] = ModelBase::toJson(m_Rating);
    }
    if(m_RuntimeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("runtime"))] = ModelBase::toJson(m_Runtime);
    }
    if(m_SeasonIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("season"))] = ModelBase::toJson(m_Season);
    }
    if(m_StudiosIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("studios"))] = ModelBase::toJson(m_Studios);
    }
    if(m_TaglineIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tagline"))] = ModelBase::toJson(m_Tagline);
    }
    if(m_TitleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("title"))] = ModelBase::toJson(m_Title);
    }
    if(m_TrailerIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("trailer"))] = ModelBase::toJson(m_Trailer);
    }
    if(m_TvShowIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tvShow"))] = ModelBase::toJson(m_TvShow);
    }
    if(m_TvShowIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tvShowId"))] = ModelBase::toJson(m_TvShowId);
    }
    if(m_UpdatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updatedAt"))] = ModelBase::toJson(m_UpdatedAt);
    }
    if(m_YearIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("year"))] = ModelBase::toJson(m_Year);
    }

    return val;
}

bool Models_Episode::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("actors"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("actors")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_Actor>> refVal_setActors;
            ok &= ModelBase::fromJson(fieldValue, refVal_setActors);
            setActors(refVal_setActors);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("banner"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("banner")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBanner;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBanner);
            setBanner(refVal_setBanner);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("certification"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("certification")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCertification;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCertification);
            setCertification(refVal_setCertification);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("deletedAt")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Gorm_DeletedAt> refVal_setDeletedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeletedAt);
            setDeletedAt(refVal_setDeletedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("directors"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("directors")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_Actor>> refVal_setDirectors;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDirectors);
            setDirectors(refVal_setDirectors);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("episode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("episode")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setEpisode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEpisode);
            setEpisode(refVal_setEpisode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("filepath"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("filepath")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFilepath;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFilepath);
            setFilepath(refVal_setFilepath);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("genres"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("genres")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_Genre>> refVal_setGenres;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGenres);
            setGenres(refVal_setGenres);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("languages"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("languages")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_Language>> refVal_setLanguages;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLanguages);
            setLanguages(refVal_setLanguages);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("originalTitle"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("originalTitle")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOriginalTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOriginalTitle);
            setOriginalTitle(refVal_setOriginalTitle);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("plot"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("plot")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPlot;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPlot);
            setPlot(refVal_setPlot);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("poster"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("poster")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPoster;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPoster);
            setPoster(refVal_setPoster);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("producers"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("producers")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_Actor>> refVal_setProducers;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProducers);
            setProducers(refVal_setProducers);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("rating"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("rating")));
        if(!fieldValue.is_null())
        {
            double refVal_setRating;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRating);
            setRating(refVal_setRating);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("runtime"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("runtime")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setRuntime;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRuntime);
            setRuntime(refVal_setRuntime);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("season"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("season")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setSeason;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSeason);
            setSeason(refVal_setSeason);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("studios"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("studios")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_Studio>> refVal_setStudios;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStudios);
            setStudios(refVal_setStudios);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tagline"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tagline")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTagline;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTagline);
            setTagline(refVal_setTagline);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitle);
            setTitle(refVal_setTitle);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("trailer"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("trailer")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTrailer;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTrailer);
            setTrailer(refVal_setTrailer);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tvShow"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tvShow")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Models_TVShow> refVal_setTvShow;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTvShow);
            setTvShow(refVal_setTvShow);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tvShowId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tvShowId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTvShowId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTvShowId);
            setTvShowId(refVal_setTvShowId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updatedAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("year"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("year")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setYear;
            ok &= ModelBase::fromJson(fieldValue, refVal_setYear);
            setYear(refVal_setYear);
            
        }
    }
    return ok;
}

void Models_Episode::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ActorsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("actors")), m_Actors));
    }
    if(m_BannerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("banner")), m_Banner));
    }
    if(m_CertificationIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("certification")), m_Certification));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
    if(m_DeletedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("deletedAt")), m_DeletedAt));
    }
    if(m_DirectorsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("directors")), m_Directors));
    }
    if(m_EpisodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("episode")), m_Episode));
    }
    if(m_FilepathIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("filepath")), m_Filepath));
    }
    if(m_GenresIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("genres")), m_Genres));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_LanguagesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("languages")), m_Languages));
    }
    if(m_OriginalTitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("originalTitle")), m_OriginalTitle));
    }
    if(m_PlotIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("plot")), m_Plot));
    }
    if(m_PosterIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("poster")), m_Poster));
    }
    if(m_ProducersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("producers")), m_Producers));
    }
    if(m_RatingIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("rating")), m_Rating));
    }
    if(m_RuntimeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("runtime")), m_Runtime));
    }
    if(m_SeasonIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("season")), m_Season));
    }
    if(m_StudiosIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("studios")), m_Studios));
    }
    if(m_TaglineIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tagline")), m_Tagline));
    }
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("title")), m_Title));
    }
    if(m_TrailerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("trailer")), m_Trailer));
    }
    if(m_TvShowIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tvShow")), m_TvShow));
    }
    if(m_TvShowIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tvShowId")), m_TvShowId));
    }
    if(m_UpdatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updatedAt")), m_UpdatedAt));
    }
    if(m_YearIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("year")), m_Year));
    }
}

bool Models_Episode::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("actors"))))
    {
        std::vector<std::shared_ptr<Models_Actor>> refVal_setActors;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("actors"))), refVal_setActors );
        setActors(refVal_setActors);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("banner"))))
    {
        utility::string_t refVal_setBanner;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("banner"))), refVal_setBanner );
        setBanner(refVal_setBanner);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("certification"))))
    {
        utility::string_t refVal_setCertification;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("certification"))), refVal_setCertification );
        setCertification(refVal_setCertification);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::string_t refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))))
    {
        std::shared_ptr<Gorm_DeletedAt> refVal_setDeletedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))), refVal_setDeletedAt );
        setDeletedAt(refVal_setDeletedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("directors"))))
    {
        std::vector<std::shared_ptr<Models_Actor>> refVal_setDirectors;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("directors"))), refVal_setDirectors );
        setDirectors(refVal_setDirectors);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("episode"))))
    {
        int32_t refVal_setEpisode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("episode"))), refVal_setEpisode );
        setEpisode(refVal_setEpisode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("filepath"))))
    {
        utility::string_t refVal_setFilepath;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("filepath"))), refVal_setFilepath );
        setFilepath(refVal_setFilepath);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("genres"))))
    {
        std::vector<std::shared_ptr<Models_Genre>> refVal_setGenres;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("genres"))), refVal_setGenres );
        setGenres(refVal_setGenres);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("languages"))))
    {
        std::vector<std::shared_ptr<Models_Language>> refVal_setLanguages;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("languages"))), refVal_setLanguages );
        setLanguages(refVal_setLanguages);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("originalTitle"))))
    {
        utility::string_t refVal_setOriginalTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("originalTitle"))), refVal_setOriginalTitle );
        setOriginalTitle(refVal_setOriginalTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("plot"))))
    {
        utility::string_t refVal_setPlot;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("plot"))), refVal_setPlot );
        setPlot(refVal_setPlot);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("poster"))))
    {
        utility::string_t refVal_setPoster;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("poster"))), refVal_setPoster );
        setPoster(refVal_setPoster);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("producers"))))
    {
        std::vector<std::shared_ptr<Models_Actor>> refVal_setProducers;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("producers"))), refVal_setProducers );
        setProducers(refVal_setProducers);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("rating"))))
    {
        double refVal_setRating;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("rating"))), refVal_setRating );
        setRating(refVal_setRating);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("runtime"))))
    {
        int32_t refVal_setRuntime;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("runtime"))), refVal_setRuntime );
        setRuntime(refVal_setRuntime);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("season"))))
    {
        int32_t refVal_setSeason;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("season"))), refVal_setSeason );
        setSeason(refVal_setSeason);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("studios"))))
    {
        std::vector<std::shared_ptr<Models_Studio>> refVal_setStudios;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("studios"))), refVal_setStudios );
        setStudios(refVal_setStudios);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tagline"))))
    {
        utility::string_t refVal_setTagline;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tagline"))), refVal_setTagline );
        setTagline(refVal_setTagline);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        utility::string_t refVal_setTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("title"))), refVal_setTitle );
        setTitle(refVal_setTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("trailer"))))
    {
        utility::string_t refVal_setTrailer;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("trailer"))), refVal_setTrailer );
        setTrailer(refVal_setTrailer);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tvShow"))))
    {
        std::shared_ptr<Models_TVShow> refVal_setTvShow;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tvShow"))), refVal_setTvShow );
        setTvShow(refVal_setTvShow);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tvShowId"))))
    {
        int32_t refVal_setTvShowId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tvShowId"))), refVal_setTvShowId );
        setTvShowId(refVal_setTvShowId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        utility::string_t refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("year"))))
    {
        int32_t refVal_setYear;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("year"))), refVal_setYear );
        setYear(refVal_setYear);
    }
    return ok;
}


std::vector<std::shared_ptr<Models_Actor>> Models_Episode::getActors() const
{
    return m_Actors;
}


void Models_Episode::setActors(const std::vector<std::shared_ptr<Models_Actor>>& value)
{
    m_Actors = value;
    m_ActorsIsSet = true;
}

bool Models_Episode::actorsIsSet() const
{
    return m_ActorsIsSet;
}

void Models_Episode::unsetActors()
{
    m_ActorsIsSet = false;
}
utility::string_t Models_Episode::getBanner() const
{
    return m_Banner;
}


void Models_Episode::setBanner(const utility::string_t& value)
{
    m_Banner = value;
    m_BannerIsSet = true;
}

bool Models_Episode::bannerIsSet() const
{
    return m_BannerIsSet;
}

void Models_Episode::unsetBanner()
{
    m_BannerIsSet = false;
}
utility::string_t Models_Episode::getCertification() const
{
    return m_Certification;
}


void Models_Episode::setCertification(const utility::string_t& value)
{
    m_Certification = value;
    m_CertificationIsSet = true;
}

bool Models_Episode::certificationIsSet() const
{
    return m_CertificationIsSet;
}

void Models_Episode::unsetCertification()
{
    m_CertificationIsSet = false;
}
utility::string_t Models_Episode::getCreatedAt() const
{
    return m_CreatedAt;
}


void Models_Episode::setCreatedAt(const utility::string_t& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool Models_Episode::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void Models_Episode::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}
std::shared_ptr<Gorm_DeletedAt> Models_Episode::getDeletedAt() const
{
    return m_DeletedAt;
}


void Models_Episode::setDeletedAt(const std::shared_ptr<Gorm_DeletedAt>& value)
{
    m_DeletedAt = value;
    m_DeletedAtIsSet = true;
}

bool Models_Episode::deletedAtIsSet() const
{
    return m_DeletedAtIsSet;
}

void Models_Episode::unsetDeletedAt()
{
    m_DeletedAtIsSet = false;
}
std::vector<std::shared_ptr<Models_Actor>> Models_Episode::getDirectors() const
{
    return m_Directors;
}


void Models_Episode::setDirectors(const std::vector<std::shared_ptr<Models_Actor>>& value)
{
    m_Directors = value;
    m_DirectorsIsSet = true;
}

bool Models_Episode::directorsIsSet() const
{
    return m_DirectorsIsSet;
}

void Models_Episode::unsetDirectors()
{
    m_DirectorsIsSet = false;
}
int32_t Models_Episode::getEpisode() const
{
    return m_Episode;
}

void Models_Episode::setEpisode(int32_t value)
{
    m_Episode = value;
    m_EpisodeIsSet = true;
}

bool Models_Episode::episodeIsSet() const
{
    return m_EpisodeIsSet;
}

void Models_Episode::unsetEpisode()
{
    m_EpisodeIsSet = false;
}
utility::string_t Models_Episode::getFilepath() const
{
    return m_Filepath;
}


void Models_Episode::setFilepath(const utility::string_t& value)
{
    m_Filepath = value;
    m_FilepathIsSet = true;
}

bool Models_Episode::filepathIsSet() const
{
    return m_FilepathIsSet;
}

void Models_Episode::unsetFilepath()
{
    m_FilepathIsSet = false;
}
std::vector<std::shared_ptr<Models_Genre>> Models_Episode::getGenres() const
{
    return m_Genres;
}


void Models_Episode::setGenres(const std::vector<std::shared_ptr<Models_Genre>>& value)
{
    m_Genres = value;
    m_GenresIsSet = true;
}

bool Models_Episode::genresIsSet() const
{
    return m_GenresIsSet;
}

void Models_Episode::unsetGenres()
{
    m_GenresIsSet = false;
}
int32_t Models_Episode::getId() const
{
    return m_Id;
}

void Models_Episode::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Models_Episode::idIsSet() const
{
    return m_IdIsSet;
}

void Models_Episode::unsetId()
{
    m_IdIsSet = false;
}
std::vector<std::shared_ptr<Models_Language>> Models_Episode::getLanguages() const
{
    return m_Languages;
}


void Models_Episode::setLanguages(const std::vector<std::shared_ptr<Models_Language>>& value)
{
    m_Languages = value;
    m_LanguagesIsSet = true;
}

bool Models_Episode::languagesIsSet() const
{
    return m_LanguagesIsSet;
}

void Models_Episode::unsetLanguages()
{
    m_LanguagesIsSet = false;
}
utility::string_t Models_Episode::getOriginalTitle() const
{
    return m_OriginalTitle;
}


void Models_Episode::setOriginalTitle(const utility::string_t& value)
{
    m_OriginalTitle = value;
    m_OriginalTitleIsSet = true;
}

bool Models_Episode::originalTitleIsSet() const
{
    return m_OriginalTitleIsSet;
}

void Models_Episode::unsetOriginalTitle()
{
    m_OriginalTitleIsSet = false;
}
utility::string_t Models_Episode::getPlot() const
{
    return m_Plot;
}


void Models_Episode::setPlot(const utility::string_t& value)
{
    m_Plot = value;
    m_PlotIsSet = true;
}

bool Models_Episode::plotIsSet() const
{
    return m_PlotIsSet;
}

void Models_Episode::unsetPlot()
{
    m_PlotIsSet = false;
}
utility::string_t Models_Episode::getPoster() const
{
    return m_Poster;
}


void Models_Episode::setPoster(const utility::string_t& value)
{
    m_Poster = value;
    m_PosterIsSet = true;
}

bool Models_Episode::posterIsSet() const
{
    return m_PosterIsSet;
}

void Models_Episode::unsetPoster()
{
    m_PosterIsSet = false;
}
std::vector<std::shared_ptr<Models_Actor>> Models_Episode::getProducers() const
{
    return m_Producers;
}


void Models_Episode::setProducers(const std::vector<std::shared_ptr<Models_Actor>>& value)
{
    m_Producers = value;
    m_ProducersIsSet = true;
}

bool Models_Episode::producersIsSet() const
{
    return m_ProducersIsSet;
}

void Models_Episode::unsetProducers()
{
    m_ProducersIsSet = false;
}
double Models_Episode::getRating() const
{
    return m_Rating;
}

void Models_Episode::setRating(double value)
{
    m_Rating = value;
    m_RatingIsSet = true;
}

bool Models_Episode::ratingIsSet() const
{
    return m_RatingIsSet;
}

void Models_Episode::unsetRating()
{
    m_RatingIsSet = false;
}
int32_t Models_Episode::getRuntime() const
{
    return m_Runtime;
}

void Models_Episode::setRuntime(int32_t value)
{
    m_Runtime = value;
    m_RuntimeIsSet = true;
}

bool Models_Episode::runtimeIsSet() const
{
    return m_RuntimeIsSet;
}

void Models_Episode::unsetRuntime()
{
    m_RuntimeIsSet = false;
}
int32_t Models_Episode::getSeason() const
{
    return m_Season;
}

void Models_Episode::setSeason(int32_t value)
{
    m_Season = value;
    m_SeasonIsSet = true;
}

bool Models_Episode::seasonIsSet() const
{
    return m_SeasonIsSet;
}

void Models_Episode::unsetSeason()
{
    m_SeasonIsSet = false;
}
std::vector<std::shared_ptr<Models_Studio>> Models_Episode::getStudios() const
{
    return m_Studios;
}


void Models_Episode::setStudios(const std::vector<std::shared_ptr<Models_Studio>>& value)
{
    m_Studios = value;
    m_StudiosIsSet = true;
}

bool Models_Episode::studiosIsSet() const
{
    return m_StudiosIsSet;
}

void Models_Episode::unsetStudios()
{
    m_StudiosIsSet = false;
}
utility::string_t Models_Episode::getTagline() const
{
    return m_Tagline;
}


void Models_Episode::setTagline(const utility::string_t& value)
{
    m_Tagline = value;
    m_TaglineIsSet = true;
}

bool Models_Episode::taglineIsSet() const
{
    return m_TaglineIsSet;
}

void Models_Episode::unsetTagline()
{
    m_TaglineIsSet = false;
}
utility::string_t Models_Episode::getTitle() const
{
    return m_Title;
}


void Models_Episode::setTitle(const utility::string_t& value)
{
    m_Title = value;
    m_TitleIsSet = true;
}

bool Models_Episode::titleIsSet() const
{
    return m_TitleIsSet;
}

void Models_Episode::unsetTitle()
{
    m_TitleIsSet = false;
}
utility::string_t Models_Episode::getTrailer() const
{
    return m_Trailer;
}


void Models_Episode::setTrailer(const utility::string_t& value)
{
    m_Trailer = value;
    m_TrailerIsSet = true;
}

bool Models_Episode::trailerIsSet() const
{
    return m_TrailerIsSet;
}

void Models_Episode::unsetTrailer()
{
    m_TrailerIsSet = false;
}
std::shared_ptr<Models_TVShow> Models_Episode::getTvShow() const
{
    return m_TvShow;
}


void Models_Episode::setTvShow(const std::shared_ptr<Models_TVShow>& value)
{
    m_TvShow = value;
    m_TvShowIsSet = true;
}

bool Models_Episode::tvShowIsSet() const
{
    return m_TvShowIsSet;
}

void Models_Episode::unsetTvShow()
{
    m_TvShowIsSet = false;
}
int32_t Models_Episode::getTvShowId() const
{
    return m_TvShowId;
}

void Models_Episode::setTvShowId(int32_t value)
{
    m_TvShowId = value;
    m_TvShowIdIsSet = true;
}

bool Models_Episode::tvShowIdIsSet() const
{
    return m_TvShowIdIsSet;
}

void Models_Episode::unsetTvShowId()
{
    m_TvShowIdIsSet = false;
}
utility::string_t Models_Episode::getUpdatedAt() const
{
    return m_UpdatedAt;
}


void Models_Episode::setUpdatedAt(const utility::string_t& value)
{
    m_UpdatedAt = value;
    m_UpdatedAtIsSet = true;
}

bool Models_Episode::updatedAtIsSet() const
{
    return m_UpdatedAtIsSet;
}

void Models_Episode::unsetUpdatedAt()
{
    m_UpdatedAtIsSet = false;
}
int32_t Models_Episode::getYear() const
{
    return m_Year;
}

void Models_Episode::setYear(int32_t value)
{
    m_Year = value;
    m_YearIsSet = true;
}

bool Models_Episode::yearIsSet() const
{
    return m_YearIsSet;
}

void Models_Episode::unsetYear()
{
    m_YearIsSet = false;
}

}
}
}
}


