/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Models_GameSave.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Models_GameSave::Models_GameSave()
{
    m_CreatedAt = utility::conversions::to_string_t("");
    m_CreatedAtIsSet = false;
    m_DeletedAtIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_file = utility::conversions::to_string_t("");
    m_fileIsSet = false;
    m_GameId = 0;
    m_GameIdIsSet = false;
    m_Id = 0;
    m_IdIsSet = false;
    m_PatchIsSet = false;
    m_PatchId = 0;
    m_PatchIdIsSet = false;
    m_ProfileId = 0;
    m_ProfileIdIsSet = false;
    m_Stream = utility::conversions::to_string_t("");
    m_StreamIsSet = false;
    m_UpdatedAt = utility::conversions::to_string_t("");
    m_UpdatedAtIsSet = false;
}

Models_GameSave::~Models_GameSave()
{
}

void Models_GameSave::validate()
{
    // TODO: implement validation
}

web::json::value Models_GameSave::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CreatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }
    if(m_DeletedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("deletedAt"))] = ModelBase::toJson(m_DeletedAt);
    }
    if(m_DescriptionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_fileIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("file"))] = ModelBase::toJson(m_file);
    }
    if(m_GameIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("gameId"))] = ModelBase::toJson(m_GameId);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_PatchIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("patch"))] = ModelBase::toJson(m_Patch);
    }
    if(m_PatchIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("patchId"))] = ModelBase::toJson(m_PatchId);
    }
    if(m_ProfileIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("profileId"))] = ModelBase::toJson(m_ProfileId);
    }
    if(m_StreamIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("stream"))] = ModelBase::toJson(m_Stream);
    }
    if(m_UpdatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updatedAt"))] = ModelBase::toJson(m_UpdatedAt);
    }

    return val;
}

bool Models_GameSave::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("deletedAt")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Gorm_DeletedAt> refVal_setDeletedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeletedAt);
            setDeletedAt(refVal_setDeletedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("file"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("file")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFile;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFile);
            setFile(refVal_setFile);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("gameId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("gameId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setGameId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGameId);
            setGameId(refVal_setGameId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("patch"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("patch")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Models_Patch> refVal_setPatch;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPatch);
            setPatch(refVal_setPatch);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("patchId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("patchId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPatchId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPatchId);
            setPatchId(refVal_setPatchId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("profileId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("profileId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setProfileId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProfileId);
            setProfileId(refVal_setProfileId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("stream"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("stream")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStream;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStream);
            setStream(refVal_setStream);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updatedAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    return ok;
}

void Models_GameSave::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
    if(m_DeletedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("deletedAt")), m_DeletedAt));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description));
    }
    if(m_fileIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("file")), m_file));
    }
    if(m_GameIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("gameId")), m_GameId));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_PatchIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("patch")), m_Patch));
    }
    if(m_PatchIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("patchId")), m_PatchId));
    }
    if(m_ProfileIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("profileId")), m_ProfileId));
    }
    if(m_StreamIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("stream")), m_Stream));
    }
    if(m_UpdatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updatedAt")), m_UpdatedAt));
    }
}

bool Models_GameSave::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::string_t refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))))
    {
        std::shared_ptr<Gorm_DeletedAt> refVal_setDeletedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))), refVal_setDeletedAt );
        setDeletedAt(refVal_setDeletedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("file"))))
    {
        utility::string_t refVal_setFile;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("file"))), refVal_setFile );
        setFile(refVal_setFile);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("gameId"))))
    {
        int32_t refVal_setGameId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("gameId"))), refVal_setGameId );
        setGameId(refVal_setGameId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("patch"))))
    {
        std::shared_ptr<Models_Patch> refVal_setPatch;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("patch"))), refVal_setPatch );
        setPatch(refVal_setPatch);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("patchId"))))
    {
        int32_t refVal_setPatchId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("patchId"))), refVal_setPatchId );
        setPatchId(refVal_setPatchId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("profileId"))))
    {
        int32_t refVal_setProfileId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("profileId"))), refVal_setProfileId );
        setProfileId(refVal_setProfileId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("stream"))))
    {
        utility::string_t refVal_setStream;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("stream"))), refVal_setStream );
        setStream(refVal_setStream);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        utility::string_t refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    return ok;
}


utility::string_t Models_GameSave::getCreatedAt() const
{
    return m_CreatedAt;
}


void Models_GameSave::setCreatedAt(const utility::string_t& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool Models_GameSave::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void Models_GameSave::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}
std::shared_ptr<Gorm_DeletedAt> Models_GameSave::getDeletedAt() const
{
    return m_DeletedAt;
}


void Models_GameSave::setDeletedAt(const std::shared_ptr<Gorm_DeletedAt>& value)
{
    m_DeletedAt = value;
    m_DeletedAtIsSet = true;
}

bool Models_GameSave::deletedAtIsSet() const
{
    return m_DeletedAtIsSet;
}

void Models_GameSave::unsetDeletedAt()
{
    m_DeletedAtIsSet = false;
}
utility::string_t Models_GameSave::getDescription() const
{
    return m_Description;
}


void Models_GameSave::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool Models_GameSave::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void Models_GameSave::unsetDescription()
{
    m_DescriptionIsSet = false;
}
utility::string_t Models_GameSave::getFile() const
{
    return m_file;
}


void Models_GameSave::setFile(const utility::string_t& value)
{
    m_file = value;
    m_fileIsSet = true;
}

bool Models_GameSave::fileIsSet() const
{
    return m_fileIsSet;
}

void Models_GameSave::unsetfile()
{
    m_fileIsSet = false;
}
int32_t Models_GameSave::getGameId() const
{
    return m_GameId;
}

void Models_GameSave::setGameId(int32_t value)
{
    m_GameId = value;
    m_GameIdIsSet = true;
}

bool Models_GameSave::gameIdIsSet() const
{
    return m_GameIdIsSet;
}

void Models_GameSave::unsetGameId()
{
    m_GameIdIsSet = false;
}
int32_t Models_GameSave::getId() const
{
    return m_Id;
}

void Models_GameSave::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Models_GameSave::idIsSet() const
{
    return m_IdIsSet;
}

void Models_GameSave::unsetId()
{
    m_IdIsSet = false;
}
std::shared_ptr<Models_Patch> Models_GameSave::getPatch() const
{
    return m_Patch;
}


void Models_GameSave::setPatch(const std::shared_ptr<Models_Patch>& value)
{
    m_Patch = value;
    m_PatchIsSet = true;
}

bool Models_GameSave::patchIsSet() const
{
    return m_PatchIsSet;
}

void Models_GameSave::unsetPatch()
{
    m_PatchIsSet = false;
}
int32_t Models_GameSave::getPatchId() const
{
    return m_PatchId;
}

void Models_GameSave::setPatchId(int32_t value)
{
    m_PatchId = value;
    m_PatchIdIsSet = true;
}

bool Models_GameSave::patchIdIsSet() const
{
    return m_PatchIdIsSet;
}

void Models_GameSave::unsetPatchId()
{
    m_PatchIdIsSet = false;
}
int32_t Models_GameSave::getProfileId() const
{
    return m_ProfileId;
}

void Models_GameSave::setProfileId(int32_t value)
{
    m_ProfileId = value;
    m_ProfileIdIsSet = true;
}

bool Models_GameSave::profileIdIsSet() const
{
    return m_ProfileIdIsSet;
}

void Models_GameSave::unsetProfileId()
{
    m_ProfileIdIsSet = false;
}
utility::string_t Models_GameSave::getStream() const
{
    return m_Stream;
}


void Models_GameSave::setStream(const utility::string_t& value)
{
    m_Stream = value;
    m_StreamIsSet = true;
}

bool Models_GameSave::streamIsSet() const
{
    return m_StreamIsSet;
}

void Models_GameSave::unsetStream()
{
    m_StreamIsSet = false;
}
utility::string_t Models_GameSave::getUpdatedAt() const
{
    return m_UpdatedAt;
}


void Models_GameSave::setUpdatedAt(const utility::string_t& value)
{
    m_UpdatedAt = value;
    m_UpdatedAtIsSet = true;
}

bool Models_GameSave::updatedAtIsSet() const
{
    return m_UpdatedAtIsSet;
}

void Models_GameSave::unsetUpdatedAt()
{
    m_UpdatedAtIsSet = false;
}

}
}
}
}


