/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Models_Game.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Models_Game::Models_Game()
{
    m_CollectionsIsSet = false;
    m_CreatedAt = utility::conversions::to_string_t("");
    m_CreatedAtIsSet = false;
    m_DefaultPatchIsSet = false;
    m_DefaultPatchId = 0;
    m_DefaultPatchIdIsSet = false;
    m_DeletedAtIsSet = false;
    m_Developer = utility::conversions::to_string_t("");
    m_DeveloperIsSet = false;
    m_file = utility::conversions::to_string_t("");
    m_fileIsSet = false;
    m_GenresIsSet = false;
    m_HltbId = 0;
    m_HltbIdIsSet = false;
    m_Id = 0;
    m_IdIsSet = false;
    m_Image = utility::conversions::to_string_t("");
    m_ImageIsSet = false;
    m_Kidgame = false;
    m_KidgameIsSet = false;
    m_Marquee = utility::conversions::to_string_t("");
    m_MarqueeIsSet = false;
    m_PatchesIsSet = false;
    m_PlatformsIsSet = false;
    m_Players = 0;
    m_PlayersIsSet = false;
    m_Plot = utility::conversions::to_string_t("");
    m_PlotIsSet = false;
    m_Publisher = utility::conversions::to_string_t("");
    m_PublisherIsSet = false;
    m_Rating = 0.0;
    m_RatingIsSet = false;
    m_Thumbnail = utility::conversions::to_string_t("");
    m_ThumbnailIsSet = false;
    m_TimeToBeat100 = 0.0;
    m_TimeToBeat100IsSet = false;
    m_TimeToBeatMain = 0.0;
    m_TimeToBeatMainIsSet = false;
    m_TimeToBeatPlus = 0.0;
    m_TimeToBeatPlusIsSet = false;
    m_Title = utility::conversions::to_string_t("");
    m_TitleIsSet = false;
    m_UpdatedAt = utility::conversions::to_string_t("");
    m_UpdatedAtIsSet = false;
    m_Video = utility::conversions::to_string_t("");
    m_VideoIsSet = false;
    m_Year = 0;
    m_YearIsSet = false;
}

Models_Game::~Models_Game()
{
}

void Models_Game::validate()
{
    // TODO: implement validation
}

web::json::value Models_Game::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CollectionsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("collections"))] = ModelBase::toJson(m_Collections);
    }
    if(m_CreatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }
    if(m_DefaultPatchIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("defaultPatch"))] = ModelBase::toJson(m_DefaultPatch);
    }
    if(m_DefaultPatchIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("defaultPatchId"))] = ModelBase::toJson(m_DefaultPatchId);
    }
    if(m_DeletedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("deletedAt"))] = ModelBase::toJson(m_DeletedAt);
    }
    if(m_DeveloperIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("developer"))] = ModelBase::toJson(m_Developer);
    }
    if(m_fileIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("file"))] = ModelBase::toJson(m_file);
    }
    if(m_GenresIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("genres"))] = ModelBase::toJson(m_Genres);
    }
    if(m_HltbIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("hltbId"))] = ModelBase::toJson(m_HltbId);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_ImageIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("image"))] = ModelBase::toJson(m_Image);
    }
    if(m_KidgameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("kidgame"))] = ModelBase::toJson(m_Kidgame);
    }
    if(m_MarqueeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("marquee"))] = ModelBase::toJson(m_Marquee);
    }
    if(m_PatchesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("patches"))] = ModelBase::toJson(m_Patches);
    }
    if(m_PlatformsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("platforms"))] = ModelBase::toJson(m_Platforms);
    }
    if(m_PlayersIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("players"))] = ModelBase::toJson(m_Players);
    }
    if(m_PlotIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("plot"))] = ModelBase::toJson(m_Plot);
    }
    if(m_PublisherIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("publisher"))] = ModelBase::toJson(m_Publisher);
    }
    if(m_RatingIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("rating"))] = ModelBase::toJson(m_Rating);
    }
    if(m_ThumbnailIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("thumbnail"))] = ModelBase::toJson(m_Thumbnail);
    }
    if(m_TimeToBeat100IsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("timeToBeat100"))] = ModelBase::toJson(m_TimeToBeat100);
    }
    if(m_TimeToBeatMainIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("timeToBeatMain"))] = ModelBase::toJson(m_TimeToBeatMain);
    }
    if(m_TimeToBeatPlusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("timeToBeatPlus"))] = ModelBase::toJson(m_TimeToBeatPlus);
    }
    if(m_TitleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("title"))] = ModelBase::toJson(m_Title);
    }
    if(m_UpdatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updatedAt"))] = ModelBase::toJson(m_UpdatedAt);
    }
    if(m_VideoIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("video"))] = ModelBase::toJson(m_Video);
    }
    if(m_YearIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("year"))] = ModelBase::toJson(m_Year);
    }

    return val;
}

bool Models_Game::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("collections"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("collections")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_Collection>> refVal_setCollections;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCollections);
            setCollections(refVal_setCollections);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("defaultPatch"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("defaultPatch")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Models_Patch> refVal_setDefaultPatch;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDefaultPatch);
            setDefaultPatch(refVal_setDefaultPatch);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("defaultPatchId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("defaultPatchId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setDefaultPatchId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDefaultPatchId);
            setDefaultPatchId(refVal_setDefaultPatchId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("deletedAt")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Gorm_DeletedAt> refVal_setDeletedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeletedAt);
            setDeletedAt(refVal_setDeletedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("developer"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("developer")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDeveloper;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeveloper);
            setDeveloper(refVal_setDeveloper);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("file"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("file")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFile;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFile);
            setFile(refVal_setFile);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("genres"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("genres")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_Genre>> refVal_setGenres;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGenres);
            setGenres(refVal_setGenres);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("hltbId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("hltbId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setHltbId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHltbId);
            setHltbId(refVal_setHltbId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("image"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("image")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setImage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setImage);
            setImage(refVal_setImage);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("kidgame"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("kidgame")));
        if(!fieldValue.is_null())
        {
            bool refVal_setKidgame;
            ok &= ModelBase::fromJson(fieldValue, refVal_setKidgame);
            setKidgame(refVal_setKidgame);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("marquee"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("marquee")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMarquee;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMarquee);
            setMarquee(refVal_setMarquee);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("patches"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("patches")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_Patch>> refVal_setPatches;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPatches);
            setPatches(refVal_setPatches);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("platforms"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("platforms")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Models_Platform>> refVal_setPlatforms;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPlatforms);
            setPlatforms(refVal_setPlatforms);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("players"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("players")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPlayers;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPlayers);
            setPlayers(refVal_setPlayers);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("plot"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("plot")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPlot;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPlot);
            setPlot(refVal_setPlot);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("publisher"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("publisher")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPublisher;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPublisher);
            setPublisher(refVal_setPublisher);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("rating"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("rating")));
        if(!fieldValue.is_null())
        {
            double refVal_setRating;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRating);
            setRating(refVal_setRating);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("thumbnail"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("thumbnail")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setThumbnail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setThumbnail);
            setThumbnail(refVal_setThumbnail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("timeToBeat100"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("timeToBeat100")));
        if(!fieldValue.is_null())
        {
            double refVal_setTimeToBeat100;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimeToBeat100);
            setTimeToBeat100(refVal_setTimeToBeat100);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("timeToBeatMain"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("timeToBeatMain")));
        if(!fieldValue.is_null())
        {
            double refVal_setTimeToBeatMain;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimeToBeatMain);
            setTimeToBeatMain(refVal_setTimeToBeatMain);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("timeToBeatPlus"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("timeToBeatPlus")));
        if(!fieldValue.is_null())
        {
            double refVal_setTimeToBeatPlus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimeToBeatPlus);
            setTimeToBeatPlus(refVal_setTimeToBeatPlus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitle);
            setTitle(refVal_setTitle);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updatedAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("video"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("video")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setVideo;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVideo);
            setVideo(refVal_setVideo);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("year"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("year")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setYear;
            ok &= ModelBase::fromJson(fieldValue, refVal_setYear);
            setYear(refVal_setYear);
            
        }
    }
    return ok;
}

void Models_Game::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CollectionsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("collections")), m_Collections));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
    if(m_DefaultPatchIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("defaultPatch")), m_DefaultPatch));
    }
    if(m_DefaultPatchIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("defaultPatchId")), m_DefaultPatchId));
    }
    if(m_DeletedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("deletedAt")), m_DeletedAt));
    }
    if(m_DeveloperIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("developer")), m_Developer));
    }
    if(m_fileIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("file")), m_file));
    }
    if(m_GenresIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("genres")), m_Genres));
    }
    if(m_HltbIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("hltbId")), m_HltbId));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_ImageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("image")), m_Image));
    }
    if(m_KidgameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("kidgame")), m_Kidgame));
    }
    if(m_MarqueeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("marquee")), m_Marquee));
    }
    if(m_PatchesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("patches")), m_Patches));
    }
    if(m_PlatformsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("platforms")), m_Platforms));
    }
    if(m_PlayersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("players")), m_Players));
    }
    if(m_PlotIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("plot")), m_Plot));
    }
    if(m_PublisherIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("publisher")), m_Publisher));
    }
    if(m_RatingIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("rating")), m_Rating));
    }
    if(m_ThumbnailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("thumbnail")), m_Thumbnail));
    }
    if(m_TimeToBeat100IsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("timeToBeat100")), m_TimeToBeat100));
    }
    if(m_TimeToBeatMainIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("timeToBeatMain")), m_TimeToBeatMain));
    }
    if(m_TimeToBeatPlusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("timeToBeatPlus")), m_TimeToBeatPlus));
    }
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("title")), m_Title));
    }
    if(m_UpdatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updatedAt")), m_UpdatedAt));
    }
    if(m_VideoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("video")), m_Video));
    }
    if(m_YearIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("year")), m_Year));
    }
}

bool Models_Game::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("collections"))))
    {
        std::vector<std::shared_ptr<Models_Collection>> refVal_setCollections;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("collections"))), refVal_setCollections );
        setCollections(refVal_setCollections);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::string_t refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("defaultPatch"))))
    {
        std::shared_ptr<Models_Patch> refVal_setDefaultPatch;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("defaultPatch"))), refVal_setDefaultPatch );
        setDefaultPatch(refVal_setDefaultPatch);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("defaultPatchId"))))
    {
        int32_t refVal_setDefaultPatchId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("defaultPatchId"))), refVal_setDefaultPatchId );
        setDefaultPatchId(refVal_setDefaultPatchId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))))
    {
        std::shared_ptr<Gorm_DeletedAt> refVal_setDeletedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("deletedAt"))), refVal_setDeletedAt );
        setDeletedAt(refVal_setDeletedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("developer"))))
    {
        utility::string_t refVal_setDeveloper;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("developer"))), refVal_setDeveloper );
        setDeveloper(refVal_setDeveloper);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("file"))))
    {
        utility::string_t refVal_setFile;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("file"))), refVal_setFile );
        setFile(refVal_setFile);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("genres"))))
    {
        std::vector<std::shared_ptr<Models_Genre>> refVal_setGenres;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("genres"))), refVal_setGenres );
        setGenres(refVal_setGenres);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("hltbId"))))
    {
        int32_t refVal_setHltbId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("hltbId"))), refVal_setHltbId );
        setHltbId(refVal_setHltbId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("image"))))
    {
        utility::string_t refVal_setImage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("image"))), refVal_setImage );
        setImage(refVal_setImage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("kidgame"))))
    {
        bool refVal_setKidgame;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("kidgame"))), refVal_setKidgame );
        setKidgame(refVal_setKidgame);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("marquee"))))
    {
        utility::string_t refVal_setMarquee;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("marquee"))), refVal_setMarquee );
        setMarquee(refVal_setMarquee);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("patches"))))
    {
        std::vector<std::shared_ptr<Models_Patch>> refVal_setPatches;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("patches"))), refVal_setPatches );
        setPatches(refVal_setPatches);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("platforms"))))
    {
        std::vector<std::shared_ptr<Models_Platform>> refVal_setPlatforms;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("platforms"))), refVal_setPlatforms );
        setPlatforms(refVal_setPlatforms);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("players"))))
    {
        int32_t refVal_setPlayers;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("players"))), refVal_setPlayers );
        setPlayers(refVal_setPlayers);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("plot"))))
    {
        utility::string_t refVal_setPlot;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("plot"))), refVal_setPlot );
        setPlot(refVal_setPlot);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("publisher"))))
    {
        utility::string_t refVal_setPublisher;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("publisher"))), refVal_setPublisher );
        setPublisher(refVal_setPublisher);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("rating"))))
    {
        double refVal_setRating;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("rating"))), refVal_setRating );
        setRating(refVal_setRating);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("thumbnail"))))
    {
        utility::string_t refVal_setThumbnail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("thumbnail"))), refVal_setThumbnail );
        setThumbnail(refVal_setThumbnail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("timeToBeat100"))))
    {
        double refVal_setTimeToBeat100;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("timeToBeat100"))), refVal_setTimeToBeat100 );
        setTimeToBeat100(refVal_setTimeToBeat100);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("timeToBeatMain"))))
    {
        double refVal_setTimeToBeatMain;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("timeToBeatMain"))), refVal_setTimeToBeatMain );
        setTimeToBeatMain(refVal_setTimeToBeatMain);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("timeToBeatPlus"))))
    {
        double refVal_setTimeToBeatPlus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("timeToBeatPlus"))), refVal_setTimeToBeatPlus );
        setTimeToBeatPlus(refVal_setTimeToBeatPlus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        utility::string_t refVal_setTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("title"))), refVal_setTitle );
        setTitle(refVal_setTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        utility::string_t refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("video"))))
    {
        utility::string_t refVal_setVideo;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("video"))), refVal_setVideo );
        setVideo(refVal_setVideo);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("year"))))
    {
        int32_t refVal_setYear;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("year"))), refVal_setYear );
        setYear(refVal_setYear);
    }
    return ok;
}


std::vector<std::shared_ptr<Models_Collection>> Models_Game::getCollections() const
{
    return m_Collections;
}


void Models_Game::setCollections(const std::vector<std::shared_ptr<Models_Collection>>& value)
{
    m_Collections = value;
    m_CollectionsIsSet = true;
}

bool Models_Game::collectionsIsSet() const
{
    return m_CollectionsIsSet;
}

void Models_Game::unsetCollections()
{
    m_CollectionsIsSet = false;
}
utility::string_t Models_Game::getCreatedAt() const
{
    return m_CreatedAt;
}


void Models_Game::setCreatedAt(const utility::string_t& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool Models_Game::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void Models_Game::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}
std::shared_ptr<Models_Patch> Models_Game::getDefaultPatch() const
{
    return m_DefaultPatch;
}


void Models_Game::setDefaultPatch(const std::shared_ptr<Models_Patch>& value)
{
    m_DefaultPatch = value;
    m_DefaultPatchIsSet = true;
}

bool Models_Game::defaultPatchIsSet() const
{
    return m_DefaultPatchIsSet;
}

void Models_Game::unsetDefaultPatch()
{
    m_DefaultPatchIsSet = false;
}
int32_t Models_Game::getDefaultPatchId() const
{
    return m_DefaultPatchId;
}

void Models_Game::setDefaultPatchId(int32_t value)
{
    m_DefaultPatchId = value;
    m_DefaultPatchIdIsSet = true;
}

bool Models_Game::defaultPatchIdIsSet() const
{
    return m_DefaultPatchIdIsSet;
}

void Models_Game::unsetDefaultPatchId()
{
    m_DefaultPatchIdIsSet = false;
}
std::shared_ptr<Gorm_DeletedAt> Models_Game::getDeletedAt() const
{
    return m_DeletedAt;
}


void Models_Game::setDeletedAt(const std::shared_ptr<Gorm_DeletedAt>& value)
{
    m_DeletedAt = value;
    m_DeletedAtIsSet = true;
}

bool Models_Game::deletedAtIsSet() const
{
    return m_DeletedAtIsSet;
}

void Models_Game::unsetDeletedAt()
{
    m_DeletedAtIsSet = false;
}
utility::string_t Models_Game::getDeveloper() const
{
    return m_Developer;
}


void Models_Game::setDeveloper(const utility::string_t& value)
{
    m_Developer = value;
    m_DeveloperIsSet = true;
}

bool Models_Game::developerIsSet() const
{
    return m_DeveloperIsSet;
}

void Models_Game::unsetDeveloper()
{
    m_DeveloperIsSet = false;
}
utility::string_t Models_Game::getFile() const
{
    return m_file;
}


void Models_Game::setFile(const utility::string_t& value)
{
    m_file = value;
    m_fileIsSet = true;
}

bool Models_Game::fileIsSet() const
{
    return m_fileIsSet;
}

void Models_Game::unsetfile()
{
    m_fileIsSet = false;
}
std::vector<std::shared_ptr<Models_Genre>> Models_Game::getGenres() const
{
    return m_Genres;
}


void Models_Game::setGenres(const std::vector<std::shared_ptr<Models_Genre>>& value)
{
    m_Genres = value;
    m_GenresIsSet = true;
}

bool Models_Game::genresIsSet() const
{
    return m_GenresIsSet;
}

void Models_Game::unsetGenres()
{
    m_GenresIsSet = false;
}
int32_t Models_Game::getHltbId() const
{
    return m_HltbId;
}

void Models_Game::setHltbId(int32_t value)
{
    m_HltbId = value;
    m_HltbIdIsSet = true;
}

bool Models_Game::hltbIdIsSet() const
{
    return m_HltbIdIsSet;
}

void Models_Game::unsetHltbId()
{
    m_HltbIdIsSet = false;
}
int32_t Models_Game::getId() const
{
    return m_Id;
}

void Models_Game::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Models_Game::idIsSet() const
{
    return m_IdIsSet;
}

void Models_Game::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t Models_Game::getImage() const
{
    return m_Image;
}


void Models_Game::setImage(const utility::string_t& value)
{
    m_Image = value;
    m_ImageIsSet = true;
}

bool Models_Game::imageIsSet() const
{
    return m_ImageIsSet;
}

void Models_Game::unsetImage()
{
    m_ImageIsSet = false;
}
bool Models_Game::isKidgame() const
{
    return m_Kidgame;
}

void Models_Game::setKidgame(bool value)
{
    m_Kidgame = value;
    m_KidgameIsSet = true;
}

bool Models_Game::kidgameIsSet() const
{
    return m_KidgameIsSet;
}

void Models_Game::unsetKidgame()
{
    m_KidgameIsSet = false;
}
utility::string_t Models_Game::getMarquee() const
{
    return m_Marquee;
}


void Models_Game::setMarquee(const utility::string_t& value)
{
    m_Marquee = value;
    m_MarqueeIsSet = true;
}

bool Models_Game::marqueeIsSet() const
{
    return m_MarqueeIsSet;
}

void Models_Game::unsetMarquee()
{
    m_MarqueeIsSet = false;
}
std::vector<std::shared_ptr<Models_Patch>> Models_Game::getPatches() const
{
    return m_Patches;
}


void Models_Game::setPatches(const std::vector<std::shared_ptr<Models_Patch>>& value)
{
    m_Patches = value;
    m_PatchesIsSet = true;
}

bool Models_Game::patchesIsSet() const
{
    return m_PatchesIsSet;
}

void Models_Game::unsetPatches()
{
    m_PatchesIsSet = false;
}
std::vector<std::shared_ptr<Models_Platform>> Models_Game::getPlatforms() const
{
    return m_Platforms;
}


void Models_Game::setPlatforms(const std::vector<std::shared_ptr<Models_Platform>>& value)
{
    m_Platforms = value;
    m_PlatformsIsSet = true;
}

bool Models_Game::platformsIsSet() const
{
    return m_PlatformsIsSet;
}

void Models_Game::unsetPlatforms()
{
    m_PlatformsIsSet = false;
}
int32_t Models_Game::getPlayers() const
{
    return m_Players;
}

void Models_Game::setPlayers(int32_t value)
{
    m_Players = value;
    m_PlayersIsSet = true;
}

bool Models_Game::playersIsSet() const
{
    return m_PlayersIsSet;
}

void Models_Game::unsetPlayers()
{
    m_PlayersIsSet = false;
}
utility::string_t Models_Game::getPlot() const
{
    return m_Plot;
}


void Models_Game::setPlot(const utility::string_t& value)
{
    m_Plot = value;
    m_PlotIsSet = true;
}

bool Models_Game::plotIsSet() const
{
    return m_PlotIsSet;
}

void Models_Game::unsetPlot()
{
    m_PlotIsSet = false;
}
utility::string_t Models_Game::getPublisher() const
{
    return m_Publisher;
}


void Models_Game::setPublisher(const utility::string_t& value)
{
    m_Publisher = value;
    m_PublisherIsSet = true;
}

bool Models_Game::publisherIsSet() const
{
    return m_PublisherIsSet;
}

void Models_Game::unsetPublisher()
{
    m_PublisherIsSet = false;
}
double Models_Game::getRating() const
{
    return m_Rating;
}

void Models_Game::setRating(double value)
{
    m_Rating = value;
    m_RatingIsSet = true;
}

bool Models_Game::ratingIsSet() const
{
    return m_RatingIsSet;
}

void Models_Game::unsetRating()
{
    m_RatingIsSet = false;
}
utility::string_t Models_Game::getThumbnail() const
{
    return m_Thumbnail;
}


void Models_Game::setThumbnail(const utility::string_t& value)
{
    m_Thumbnail = value;
    m_ThumbnailIsSet = true;
}

bool Models_Game::thumbnailIsSet() const
{
    return m_ThumbnailIsSet;
}

void Models_Game::unsetThumbnail()
{
    m_ThumbnailIsSet = false;
}
double Models_Game::getTimeToBeat100() const
{
    return m_TimeToBeat100;
}

void Models_Game::setTimeToBeat100(double value)
{
    m_TimeToBeat100 = value;
    m_TimeToBeat100IsSet = true;
}

bool Models_Game::timeToBeat100IsSet() const
{
    return m_TimeToBeat100IsSet;
}

void Models_Game::unsetTimeToBeat100()
{
    m_TimeToBeat100IsSet = false;
}
double Models_Game::getTimeToBeatMain() const
{
    return m_TimeToBeatMain;
}

void Models_Game::setTimeToBeatMain(double value)
{
    m_TimeToBeatMain = value;
    m_TimeToBeatMainIsSet = true;
}

bool Models_Game::timeToBeatMainIsSet() const
{
    return m_TimeToBeatMainIsSet;
}

void Models_Game::unsetTimeToBeatMain()
{
    m_TimeToBeatMainIsSet = false;
}
double Models_Game::getTimeToBeatPlus() const
{
    return m_TimeToBeatPlus;
}

void Models_Game::setTimeToBeatPlus(double value)
{
    m_TimeToBeatPlus = value;
    m_TimeToBeatPlusIsSet = true;
}

bool Models_Game::timeToBeatPlusIsSet() const
{
    return m_TimeToBeatPlusIsSet;
}

void Models_Game::unsetTimeToBeatPlus()
{
    m_TimeToBeatPlusIsSet = false;
}
utility::string_t Models_Game::getTitle() const
{
    return m_Title;
}


void Models_Game::setTitle(const utility::string_t& value)
{
    m_Title = value;
    m_TitleIsSet = true;
}

bool Models_Game::titleIsSet() const
{
    return m_TitleIsSet;
}

void Models_Game::unsetTitle()
{
    m_TitleIsSet = false;
}
utility::string_t Models_Game::getUpdatedAt() const
{
    return m_UpdatedAt;
}


void Models_Game::setUpdatedAt(const utility::string_t& value)
{
    m_UpdatedAt = value;
    m_UpdatedAtIsSet = true;
}

bool Models_Game::updatedAtIsSet() const
{
    return m_UpdatedAtIsSet;
}

void Models_Game::unsetUpdatedAt()
{
    m_UpdatedAtIsSet = false;
}
utility::string_t Models_Game::getVideo() const
{
    return m_Video;
}


void Models_Game::setVideo(const utility::string_t& value)
{
    m_Video = value;
    m_VideoIsSet = true;
}

bool Models_Game::videoIsSet() const
{
    return m_VideoIsSet;
}

void Models_Game::unsetVideo()
{
    m_VideoIsSet = false;
}
int32_t Models_Game::getYear() const
{
    return m_Year;
}

void Models_Game::setYear(int32_t value)
{
    m_Year = value;
    m_YearIsSet = true;
}

bool Models_Game::yearIsSet() const
{
    return m_YearIsSet;
}

void Models_Game::unsetYear()
{
    m_YearIsSet = false;
}

}
}
}
}


