/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Models_Play.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Models_Play::Models_Play()
{
    m_ClientIp = utility::conversions::to_string_t("");
    m_ClientIpIsSet = false;
    m_GameIsSet = false;
    m_GameId = 0;
    m_GameIdIsSet = false;
    m_Id = 0;
    m_IdIsSet = false;
    m_PlayedAt = utility::conversions::to_string_t("");
    m_PlayedAtIsSet = false;
    m_ProfileId = 0;
    m_ProfileIdIsSet = false;
}

Models_Play::~Models_Play()
{
}

void Models_Play::validate()
{
    // TODO: implement validation
}

web::json::value Models_Play::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ClientIpIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("clientIp"))] = ModelBase::toJson(m_ClientIp);
    }
    if(m_GameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("game"))] = ModelBase::toJson(m_Game);
    }
    if(m_GameIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("gameId"))] = ModelBase::toJson(m_GameId);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_PlayedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("playedAt"))] = ModelBase::toJson(m_PlayedAt);
    }
    if(m_ProfileIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("profileId"))] = ModelBase::toJson(m_ProfileId);
    }

    return val;
}

bool Models_Play::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("clientIp"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("clientIp")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setClientIp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setClientIp);
            setClientIp(refVal_setClientIp);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("game"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("game")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Models_Game> refVal_setGame;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGame);
            setGame(refVal_setGame);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("gameId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("gameId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setGameId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGameId);
            setGameId(refVal_setGameId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("playedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("playedAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPlayedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPlayedAt);
            setPlayedAt(refVal_setPlayedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("profileId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("profileId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setProfileId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProfileId);
            setProfileId(refVal_setProfileId);
            
        }
    }
    return ok;
}

void Models_Play::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ClientIpIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("clientIp")), m_ClientIp));
    }
    if(m_GameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("game")), m_Game));
    }
    if(m_GameIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("gameId")), m_GameId));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_PlayedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("playedAt")), m_PlayedAt));
    }
    if(m_ProfileIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("profileId")), m_ProfileId));
    }
}

bool Models_Play::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("clientIp"))))
    {
        utility::string_t refVal_setClientIp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("clientIp"))), refVal_setClientIp );
        setClientIp(refVal_setClientIp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("game"))))
    {
        std::shared_ptr<Models_Game> refVal_setGame;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("game"))), refVal_setGame );
        setGame(refVal_setGame);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("gameId"))))
    {
        int32_t refVal_setGameId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("gameId"))), refVal_setGameId );
        setGameId(refVal_setGameId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("playedAt"))))
    {
        utility::string_t refVal_setPlayedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("playedAt"))), refVal_setPlayedAt );
        setPlayedAt(refVal_setPlayedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("profileId"))))
    {
        int32_t refVal_setProfileId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("profileId"))), refVal_setProfileId );
        setProfileId(refVal_setProfileId);
    }
    return ok;
}


utility::string_t Models_Play::getClientIp() const
{
    return m_ClientIp;
}


void Models_Play::setClientIp(const utility::string_t& value)
{
    m_ClientIp = value;
    m_ClientIpIsSet = true;
}

bool Models_Play::clientIpIsSet() const
{
    return m_ClientIpIsSet;
}

void Models_Play::unsetClientIp()
{
    m_ClientIpIsSet = false;
}
std::shared_ptr<Models_Game> Models_Play::getGame() const
{
    return m_Game;
}


void Models_Play::setGame(const std::shared_ptr<Models_Game>& value)
{
    m_Game = value;
    m_GameIsSet = true;
}

bool Models_Play::gameIsSet() const
{
    return m_GameIsSet;
}

void Models_Play::unsetGame()
{
    m_GameIsSet = false;
}
int32_t Models_Play::getGameId() const
{
    return m_GameId;
}

void Models_Play::setGameId(int32_t value)
{
    m_GameId = value;
    m_GameIdIsSet = true;
}

bool Models_Play::gameIdIsSet() const
{
    return m_GameIdIsSet;
}

void Models_Play::unsetGameId()
{
    m_GameIdIsSet = false;
}
int32_t Models_Play::getId() const
{
    return m_Id;
}

void Models_Play::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Models_Play::idIsSet() const
{
    return m_IdIsSet;
}

void Models_Play::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t Models_Play::getPlayedAt() const
{
    return m_PlayedAt;
}


void Models_Play::setPlayedAt(const utility::string_t& value)
{
    m_PlayedAt = value;
    m_PlayedAtIsSet = true;
}

bool Models_Play::playedAtIsSet() const
{
    return m_PlayedAtIsSet;
}

void Models_Play::unsetPlayedAt()
{
    m_PlayedAtIsSet = false;
}
int32_t Models_Play::getProfileId() const
{
    return m_ProfileId;
}

void Models_Play::setProfileId(int32_t value)
{
    m_ProfileId = value;
    m_ProfileIdIsSet = true;
}

bool Models_Play::profileIdIsSet() const
{
    return m_ProfileIdIsSet;
}

void Models_Play::unsetProfileId()
{
    m_ProfileIdIsSet = false;
}

}
}
}
}


