/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Routes_TokenRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Routes_TokenRequest::Routes_TokenRequest()
{
    m_Pin = utility::conversions::to_string_t("");
    m_PinIsSet = false;
    m_ProfileId = 0;
    m_ProfileIdIsSet = false;
}

Routes_TokenRequest::~Routes_TokenRequest()
{
}

void Routes_TokenRequest::validate()
{
    // TODO: implement validation
}

web::json::value Routes_TokenRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PinIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("pin"))] = ModelBase::toJson(m_Pin);
    }
    if(m_ProfileIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("profileId"))] = ModelBase::toJson(m_ProfileId);
    }

    return val;
}

bool Routes_TokenRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("pin"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("pin")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPin;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPin);
            setPin(refVal_setPin);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("profileId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("profileId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setProfileId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProfileId);
            setProfileId(refVal_setProfileId);
            
        }
    }
    return ok;
}

void Routes_TokenRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PinIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("pin")), m_Pin));
    }
    if(m_ProfileIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("profileId")), m_ProfileId));
    }
}

bool Routes_TokenRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("pin"))))
    {
        utility::string_t refVal_setPin;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("pin"))), refVal_setPin );
        setPin(refVal_setPin);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("profileId"))))
    {
        int32_t refVal_setProfileId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("profileId"))), refVal_setProfileId );
        setProfileId(refVal_setProfileId);
    }
    return ok;
}


utility::string_t Routes_TokenRequest::getPin() const
{
    return m_Pin;
}


void Routes_TokenRequest::setPin(const utility::string_t& value)
{
    m_Pin = value;
    m_PinIsSet = true;
}

bool Routes_TokenRequest::pinIsSet() const
{
    return m_PinIsSet;
}

void Routes_TokenRequest::unsetPin()
{
    m_PinIsSet = false;
}
int32_t Routes_TokenRequest::getProfileId() const
{
    return m_ProfileId;
}

void Routes_TokenRequest::setProfileId(int32_t value)
{
    m_ProfileId = value;
    m_ProfileIdIsSet = true;
}

bool Routes_TokenRequest::profileIdIsSet() const
{
    return m_ProfileIdIsSet;
}

void Routes_TokenRequest::unsetProfileId()
{
    m_ProfileIdIsSet = false;
}

}
}
}
}


