/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Routes_ImportRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Routes_ImportRequest::Routes_ImportRequest()
{
    m_Path = utility::conversions::to_string_t("");
    m_PathIsSet = false;
}

Routes_ImportRequest::~Routes_ImportRequest()
{
}

void Routes_ImportRequest::validate()
{
    // TODO: implement validation
}

web::json::value Routes_ImportRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PathIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("path"))] = ModelBase::toJson(m_Path);
    }

    return val;
}

bool Routes_ImportRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("path"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("path")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPath;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPath);
            setPath(refVal_setPath);
            
        }
    }
    return ok;
}

void Routes_ImportRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PathIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("path")), m_Path));
    }
}

bool Routes_ImportRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("path"))))
    {
        utility::string_t refVal_setPath;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("path"))), refVal_setPath );
        setPath(refVal_setPath);
    }
    return ok;
}


utility::string_t Routes_ImportRequest::getPath() const
{
    return m_Path;
}


void Routes_ImportRequest::setPath(const utility::string_t& value)
{
    m_Path = value;
    m_PathIsSet = true;
}

bool Routes_ImportRequest::pathIsSet() const
{
    return m_PathIsSet;
}

void Routes_ImportRequest::unsetPath()
{
    m_PathIsSet = false;
}

}
}
}
}


