/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Routes_ProfileRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Routes_ProfileRequest::Routes_ProfileRequest()
{
    m_Avatar = utility::conversions::to_string_t("");
    m_AvatarIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Pin = utility::conversions::to_string_t("");
    m_PinIsSet = false;
    m_Theme = utility::conversions::to_string_t("");
    m_ThemeIsSet = false;
    m_Type = utility::conversions::to_string_t("");
    m_TypeIsSet = false;
}

Routes_ProfileRequest::~Routes_ProfileRequest()
{
}

void Routes_ProfileRequest::validate()
{
    // TODO: implement validation
}

web::json::value Routes_ProfileRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AvatarIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("avatar"))] = ModelBase::toJson(m_Avatar);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_PinIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("pin"))] = ModelBase::toJson(m_Pin);
    }
    if(m_ThemeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("theme"))] = ModelBase::toJson(m_Theme);
    }
    if(m_TypeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("type"))] = ModelBase::toJson(m_Type);
    }

    return val;
}

bool Routes_ProfileRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("avatar"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("avatar")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAvatar;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAvatar);
            setAvatar(refVal_setAvatar);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("pin"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("pin")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPin;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPin);
            setPin(refVal_setPin);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("theme"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("theme")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTheme;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTheme);
            setTheme(refVal_setTheme);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setType);
            setType(refVal_setType);
            
        }
    }
    return ok;
}

void Routes_ProfileRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AvatarIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("avatar")), m_Avatar));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_PinIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("pin")), m_Pin));
    }
    if(m_ThemeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("theme")), m_Theme));
    }
    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("type")), m_Type));
    }
}

bool Routes_ProfileRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("avatar"))))
    {
        utility::string_t refVal_setAvatar;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("avatar"))), refVal_setAvatar );
        setAvatar(refVal_setAvatar);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("pin"))))
    {
        utility::string_t refVal_setPin;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("pin"))), refVal_setPin );
        setPin(refVal_setPin);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("theme"))))
    {
        utility::string_t refVal_setTheme;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("theme"))), refVal_setTheme );
        setTheme(refVal_setTheme);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        utility::string_t refVal_setType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("type"))), refVal_setType );
        setType(refVal_setType);
    }
    return ok;
}


utility::string_t Routes_ProfileRequest::getAvatar() const
{
    return m_Avatar;
}


void Routes_ProfileRequest::setAvatar(const utility::string_t& value)
{
    m_Avatar = value;
    m_AvatarIsSet = true;
}

bool Routes_ProfileRequest::avatarIsSet() const
{
    return m_AvatarIsSet;
}

void Routes_ProfileRequest::unsetAvatar()
{
    m_AvatarIsSet = false;
}
utility::string_t Routes_ProfileRequest::getName() const
{
    return m_Name;
}


void Routes_ProfileRequest::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Routes_ProfileRequest::nameIsSet() const
{
    return m_NameIsSet;
}

void Routes_ProfileRequest::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t Routes_ProfileRequest::getPin() const
{
    return m_Pin;
}


void Routes_ProfileRequest::setPin(const utility::string_t& value)
{
    m_Pin = value;
    m_PinIsSet = true;
}

bool Routes_ProfileRequest::pinIsSet() const
{
    return m_PinIsSet;
}

void Routes_ProfileRequest::unsetPin()
{
    m_PinIsSet = false;
}
utility::string_t Routes_ProfileRequest::getTheme() const
{
    return m_Theme;
}


void Routes_ProfileRequest::setTheme(const utility::string_t& value)
{
    m_Theme = value;
    m_ThemeIsSet = true;
}

bool Routes_ProfileRequest::themeIsSet() const
{
    return m_ThemeIsSet;
}

void Routes_ProfileRequest::unsetTheme()
{
    m_ThemeIsSet = false;
}
utility::string_t Routes_ProfileRequest::getType() const
{
    return m_Type;
}


void Routes_ProfileRequest::setType(const utility::string_t& value)
{
    m_Type = value;
    m_TypeIsSet = true;
}

bool Routes_ProfileRequest::typeIsSet() const
{
    return m_TypeIsSet;
}

void Routes_ProfileRequest::unsetType()
{
    m_TypeIsSet = false;
}

}
}
}
}


