/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Routes_ImportGamesRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Routes_ImportGamesRequest::Routes_ImportGamesRequest()
{
    m_Path = utility::conversions::to_string_t("");
    m_PathIsSet = false;
    m_Platform = utility::conversions::to_string_t("");
    m_PlatformIsSet = false;
}

Routes_ImportGamesRequest::~Routes_ImportGamesRequest()
{
}

void Routes_ImportGamesRequest::validate()
{
    // TODO: implement validation
}

web::json::value Routes_ImportGamesRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PathIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("path"))] = ModelBase::toJson(m_Path);
    }
    if(m_PlatformIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("platform"))] = ModelBase::toJson(m_Platform);
    }

    return val;
}

bool Routes_ImportGamesRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("path"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("path")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPath;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPath);
            setPath(refVal_setPath);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("platform"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("platform")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPlatform;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPlatform);
            setPlatform(refVal_setPlatform);
            
        }
    }
    return ok;
}

void Routes_ImportGamesRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PathIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("path")), m_Path));
    }
    if(m_PlatformIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("platform")), m_Platform));
    }
}

bool Routes_ImportGamesRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("path"))))
    {
        utility::string_t refVal_setPath;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("path"))), refVal_setPath );
        setPath(refVal_setPath);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("platform"))))
    {
        utility::string_t refVal_setPlatform;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("platform"))), refVal_setPlatform );
        setPlatform(refVal_setPlatform);
    }
    return ok;
}


utility::string_t Routes_ImportGamesRequest::getPath() const
{
    return m_Path;
}


void Routes_ImportGamesRequest::setPath(const utility::string_t& value)
{
    m_Path = value;
    m_PathIsSet = true;
}

bool Routes_ImportGamesRequest::pathIsSet() const
{
    return m_PathIsSet;
}

void Routes_ImportGamesRequest::unsetPath()
{
    m_PathIsSet = false;
}
utility::string_t Routes_ImportGamesRequest::getPlatform() const
{
    return m_Platform;
}


void Routes_ImportGamesRequest::setPlatform(const utility::string_t& value)
{
    m_Platform = value;
    m_PlatformIsSet = true;
}

bool Routes_ImportGamesRequest::platformIsSet() const
{
    return m_PlatformIsSet;
}

void Routes_ImportGamesRequest::unsetPlatform()
{
    m_PlatformIsSet = false;
}

}
}
}
}


