/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "danflix_client/model/Routes_GenerationInfo.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Routes_GenerationInfo::Routes_GenerationInfo()
{
    m_EraName = utility::conversions::to_string_t("");
    m_EraNameIsSet = false;
    m_Id = 0;
    m_IdIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Years = utility::conversions::to_string_t("");
    m_YearsIsSet = false;
}

Routes_GenerationInfo::~Routes_GenerationInfo()
{
}

void Routes_GenerationInfo::validate()
{
    // TODO: implement validation
}

web::json::value Routes_GenerationInfo::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_EraNameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("eraName"))] = ModelBase::toJson(m_EraName);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_YearsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("years"))] = ModelBase::toJson(m_Years);
    }

    return val;
}

bool Routes_GenerationInfo::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("eraName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("eraName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEraName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEraName);
            setEraName(refVal_setEraName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("years"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("years")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setYears;
            ok &= ModelBase::fromJson(fieldValue, refVal_setYears);
            setYears(refVal_setYears);
            
        }
    }
    return ok;
}

void Routes_GenerationInfo::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_EraNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("eraName")), m_EraName));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_YearsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("years")), m_Years));
    }
}

bool Routes_GenerationInfo::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("eraName"))))
    {
        utility::string_t refVal_setEraName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("eraName"))), refVal_setEraName );
        setEraName(refVal_setEraName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("years"))))
    {
        utility::string_t refVal_setYears;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("years"))), refVal_setYears );
        setYears(refVal_setYears);
    }
    return ok;
}


utility::string_t Routes_GenerationInfo::getEraName() const
{
    return m_EraName;
}


void Routes_GenerationInfo::setEraName(const utility::string_t& value)
{
    m_EraName = value;
    m_EraNameIsSet = true;
}

bool Routes_GenerationInfo::eraNameIsSet() const
{
    return m_EraNameIsSet;
}

void Routes_GenerationInfo::unsetEraName()
{
    m_EraNameIsSet = false;
}
int32_t Routes_GenerationInfo::getId() const
{
    return m_Id;
}

void Routes_GenerationInfo::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Routes_GenerationInfo::idIsSet() const
{
    return m_IdIsSet;
}

void Routes_GenerationInfo::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t Routes_GenerationInfo::getName() const
{
    return m_Name;
}


void Routes_GenerationInfo::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Routes_GenerationInfo::nameIsSet() const
{
    return m_NameIsSet;
}

void Routes_GenerationInfo::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t Routes_GenerationInfo::getYears() const
{
    return m_Years;
}


void Routes_GenerationInfo::setYears(const utility::string_t& value)
{
    m_Years = value;
    m_YearsIsSet = true;
}

bool Routes_GenerationInfo::yearsIsSet() const
{
    return m_YearsIsSet;
}

void Routes_GenerationInfo::unsetYears()
{
    m_YearsIsSet = false;
}

}
}
}
}


