/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Models_GameSave.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Models_GameSave_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Models_GameSave_H_

#include <boost/optional.hpp>

#include "danflix_client/ModelBase.h"

#include "danflix_client/model/Gorm_DeletedAt.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Gorm_DeletedAt;


class  Models_GameSave
    : public ModelBase
{
public:
    Models_GameSave();
    virtual ~Models_GameSave();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Models_GameSave members


    utility::string_t getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();
    void setCreatedAt(const utility::string_t& value);

    std::shared_ptr<Gorm_DeletedAt> getDeletedAt() const;
    bool deletedAtIsSet() const;
    void unsetDeletedAt();
    void setDeletedAt(const std::shared_ptr<Gorm_DeletedAt>& value);

    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();
    void setDescription(const utility::string_t& value);

    int32_t getGameId() const;
    bool gameIdIsSet() const;
    void unsetGameId();
    void setGameId(int32_t value);

    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    /// <summary>
    /// Optional, to track patched versions
    /// </summary>
    utility::string_t getPatchId() const;
    bool patchIdIsSet() const;
    void unsetPatchId();
    void setPatchId(const utility::string_t& value);

    /// <summary>
    /// Filesystem path
    /// </summary>
    utility::string_t getPath() const;
    bool pathIsSet() const;
    void unsetPath();
    void setPath(const utility::string_t& value);

    int32_t getProfileId() const;
    bool profileIdIsSet() const;
    void unsetProfileId();
    void setProfileId(int32_t value);

    utility::string_t getUpdatedAt() const;
    bool updatedAtIsSet() const;
    void unsetUpdatedAt();
    void setUpdatedAt(const utility::string_t& value);


protected:
    utility::string_t m_CreatedAt;
    bool m_CreatedAtIsSet;

    std::shared_ptr<Gorm_DeletedAt> m_DeletedAt;
    bool m_DeletedAtIsSet;

    utility::string_t m_Description;
    bool m_DescriptionIsSet;

    int32_t m_GameId;
    bool m_GameIdIsSet;

    int32_t m_Id;
    bool m_IdIsSet;

    utility::string_t m_PatchId;
    bool m_PatchIdIsSet;

    utility::string_t m_Path;
    bool m_PathIsSet;

    int32_t m_ProfileId;
    bool m_ProfileIdIsSet;

    utility::string_t m_UpdatedAt;
    bool m_UpdatedAtIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Models_GameSave_H_ */
