/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Models_Genre.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Genre_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Genre_H_

#include <boost/optional.hpp>

#include "danflix_client/ModelBase.h"

#include "danflix_client/model/Models_TVShow.h"
#include <cpprest/details/basic_types.h>
#include "danflix_client/model/Models_Movie.h"
#include <vector>
#include "danflix_client/model/Models_Game.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Models_Game;
class Models_Movie;
class Models_TVShow;


class  Models_Genre
    : public ModelBase
{
public:
    Models_Genre();
    virtual ~Models_Genre();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Models_Genre members


    std::vector<std::shared_ptr<Models_Game>> getGames() const;
    bool gamesIsSet() const;
    void unsetGames();
    void setGames(const std::vector<std::shared_ptr<Models_Game>>& value);

    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    std::vector<std::shared_ptr<Models_Movie>> getMovies() const;
    bool moviesIsSet() const;
    void unsetMovies();
    void setMovies(const std::vector<std::shared_ptr<Models_Movie>>& value);

    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    std::vector<std::shared_ptr<Models_TVShow>> getTvShows() const;
    bool tvShowsIsSet() const;
    void unsetTvShows();
    void setTvShows(const std::vector<std::shared_ptr<Models_TVShow>>& value);


protected:
    std::vector<std::shared_ptr<Models_Game>> m_Games;
    bool m_GamesIsSet;

    int32_t m_Id;
    bool m_IdIsSet;

    std::vector<std::shared_ptr<Models_Movie>> m_Movies;
    bool m_MoviesIsSet;

    utility::string_t m_Name;
    bool m_NameIsSet;

    std::vector<std::shared_ptr<Models_TVShow>> m_TvShows;
    bool m_TvShowsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Genre_H_ */
