/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Models_Patch.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Patch_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Patch_H_

#include <boost/optional.hpp>

#include "danflix_client/ModelBase.h"

#include "danflix_client/model/Gorm_DeletedAt.h"
#include <cpprest/details/basic_types.h>
#include "danflix_client/model/Models_Game.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Gorm_DeletedAt;
class Models_Game;


class  Models_Patch
    : public ModelBase
{
public:
    Models_Patch();
    virtual ~Models_Patch();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Models_Patch members


    utility::string_t getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();
    void setCreatedAt(const utility::string_t& value);

    std::shared_ptr<Gorm_DeletedAt> getDeletedAt() const;
    bool deletedAtIsSet() const;
    void unsetDeletedAt();
    void setDeletedAt(const std::shared_ptr<Gorm_DeletedAt>& value);

    /// <summary>
    /// From TGDB
    /// </summary>
    utility::string_t getDeveloper() const;
    bool developerIsSet() const;
    void unsetDeveloper();
    void setDeveloper(const utility::string_t& value);

    utility::string_t getFile() const;
    bool fileIsSet() const;
    void unsetfile();
    void setFile(const utility::string_t& value);

    /// <summary>
    /// Relationships
    /// </summary>
    std::shared_ptr<Models_Game> getGame() const;
    bool gameIsSet() const;
    void unsetGame();
    void setGame(const std::shared_ptr<Models_Game>& value);

    int32_t getGameId() const;
    bool gameIdIsSet() const;
    void unsetGameId();
    void setGameId(int32_t value);

    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    /// <summary>
    /// Quality of Life patch
    /// </summary>
    bool isIsQoL() const;
    bool isQoLIsSet() const;
    void unsetIsQoL();
    void setIsQoL(bool value);

    /// <summary>
    /// From TGDB
    /// </summary>
    utility::string_t getOverview() const;
    bool overviewIsSet() const;
    void unsetOverview();
    void setOverview(const utility::string_t& value);

    /// <summary>
    /// Display control flags
    /// </summary>
    bool isPromoted() const;
    bool promotedIsSet() const;
    void unsetPromoted();
    void setPromoted(bool value);

    /// <summary>
    /// From TGDB
    /// </summary>
    utility::string_t getReleaseDate() const;
    bool releaseDateIsSet() const;
    void unsetReleaseDate();
    void setReleaseDate(const utility::string_t& value);

    /// <summary>
    /// From TGDB
    /// </summary>
    int32_t getTgdbId() const;
    bool tgdbIdIsSet() const;
    void unsetTgdbId();
    void setTgdbId(int32_t value);

    /// <summary>
    /// Derived from filename or metadata
    /// </summary>
    utility::string_t getTitle() const;
    bool titleIsSet() const;
    void unsetTitle();
    void setTitle(const utility::string_t& value);

    utility::string_t getUpdatedAt() const;
    bool updatedAtIsSet() const;
    void unsetUpdatedAt();
    void setUpdatedAt(const utility::string_t& value);

    /// <summary>
    /// Optional version info
    /// </summary>
    utility::string_t getVersion() const;
    bool versionIsSet() const;
    void unsetVersion();
    void setVersion(const utility::string_t& value);


protected:
    utility::string_t m_CreatedAt;
    bool m_CreatedAtIsSet;

    std::shared_ptr<Gorm_DeletedAt> m_DeletedAt;
    bool m_DeletedAtIsSet;

    utility::string_t m_Developer;
    bool m_DeveloperIsSet;

    utility::string_t m_file;
    bool m_fileIsSet;

    std::shared_ptr<Models_Game> m_Game;
    bool m_GameIsSet;

    int32_t m_GameId;
    bool m_GameIdIsSet;

    int32_t m_Id;
    bool m_IdIsSet;

    bool m_IsQoL;
    bool m_IsQoLIsSet;

    utility::string_t m_Overview;
    bool m_OverviewIsSet;

    bool m_Promoted;
    bool m_PromotedIsSet;

    utility::string_t m_ReleaseDate;
    bool m_ReleaseDateIsSet;

    int32_t m_TgdbId;
    bool m_TgdbIdIsSet;

    utility::string_t m_Title;
    bool m_TitleIsSet;

    utility::string_t m_UpdatedAt;
    bool m_UpdatedAtIsSet;

    utility::string_t m_Version;
    bool m_VersionIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Patch_H_ */
