/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Models_Command.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Command_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Command_H_

#include <boost/optional.hpp>

#include "danflix_client/ModelBase.h"

#include "danflix_client/Object.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Models_Command
    : public ModelBase
{
public:
    Models_Command();
    virtual ~Models_Command();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Models_Command members


    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(const utility::string_t& value);

    /// <summary>
    /// Flexible payload
    /// </summary>
    std::shared_ptr<Object> getPayload() const;
    bool payloadIsSet() const;
    void unsetPayload();
    void setPayload(const std::shared_ptr<Object>& value);

    utility::string_t getSentAt() const;
    bool sentAtIsSet() const;
    void unsetSentAt();
    void setSentAt(const utility::string_t& value);

    /// <summary>
    /// e.g., \&quot;PAUSE\&quot;, \&quot;RESUME\&quot;, \&quot;SEEK\&quot;, \&quot;MESSAGE\&quot;
    /// </summary>
    utility::string_t getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(const utility::string_t& value);


protected:
    utility::string_t m_Id;
    bool m_IdIsSet;

    std::shared_ptr<Object> m_Payload;
    bool m_PayloadIsSet;

    utility::string_t m_SentAt;
    bool m_SentAtIsSet;

    utility::string_t m_Type;
    bool m_TypeIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Command_H_ */
