/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Models_Movie.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Movie_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Movie_H_

#include <boost/optional.hpp>

#include "danflix_client/ModelBase.h"

#include "danflix_client/model/Models_Studio.h"
#include "danflix_client/model/Models_Genre.h"
#include "danflix_client/Object.h"
#include "danflix_client/model/Models_Language.h"
#include "danflix_client/model/Gorm_DeletedAt.h"
#include "danflix_client/model/Models_Actor.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Models_Actor;
class Gorm_DeletedAt;
class Models_Genre;
class Models_Language;
class Models_Studio;


class  Models_Movie
    : public ModelBase
{
public:
    Models_Movie();
    virtual ~Models_Movie();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Models_Movie members


    std::vector<std::shared_ptr<Models_Actor>> getActors() const;
    bool actorsIsSet() const;
    void unsetActors();
    void setActors(const std::vector<std::shared_ptr<Models_Actor>>& value);

    /// <summary>
    /// path/url
    /// </summary>
    utility::string_t getBanner() const;
    bool bannerIsSet() const;
    void unsetBanner();
    void setBanner(const utility::string_t& value);

    utility::string_t getCertification() const;
    bool certificationIsSet() const;
    void unsetCertification();
    void setCertification(const utility::string_t& value);

    utility::string_t getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();
    void setCreatedAt(const utility::string_t& value);

    std::shared_ptr<Gorm_DeletedAt> getDeletedAt() const;
    bool deletedAtIsSet() const;
    void unsetDeletedAt();
    void setDeletedAt(const std::shared_ptr<Gorm_DeletedAt>& value);

    std::vector<std::shared_ptr<Models_Actor>> getDirectors() const;
    bool directorsIsSet() const;
    void unsetDirectors();
    void setDirectors(const std::vector<std::shared_ptr<Models_Actor>>& value);

    /// <summary>
    /// path to the video file
    /// </summary>
    utility::string_t getFilepath() const;
    bool filepathIsSet() const;
    void unsetFilepath();
    void setFilepath(const utility::string_t& value);

    /// <summary>
    /// Relations
    /// </summary>
    std::vector<std::shared_ptr<Models_Genre>> getGenres() const;
    bool genresIsSet() const;
    void unsetGenres();
    void setGenres(const std::vector<std::shared_ptr<Models_Genre>>& value);

    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    std::vector<std::shared_ptr<Models_Language>> getLanguages() const;
    bool languagesIsSet() const;
    void unsetLanguages();
    void setLanguages(const std::vector<std::shared_ptr<Models_Language>>& value);

    utility::string_t getOriginalTitle() const;
    bool originalTitleIsSet() const;
    void unsetOriginalTitle();
    void setOriginalTitle(const utility::string_t& value);

    utility::string_t getPlot() const;
    bool plotIsSet() const;
    void unsetPlot();
    void setPlot(const utility::string_t& value);

    /// <summary>
    /// path/url
    /// </summary>
    utility::string_t getPoster() const;
    bool posterIsSet() const;
    void unsetPoster();
    void setPoster(const utility::string_t& value);

    std::vector<std::shared_ptr<Models_Actor>> getProducers() const;
    bool producersIsSet() const;
    void unsetProducers();
    void setProducers(const std::vector<std::shared_ptr<Models_Actor>>& value);

    double getRating() const;
    bool ratingIsSet() const;
    void unsetRating();
    void setRating(double value);

    std::shared_ptr<Object> getResume() const;
    bool resumeIsSet() const;
    void unsetResume();
    void setResume(const std::shared_ptr<Object>& value);

    /// <summary>
    /// in minutes
    /// </summary>
    int32_t getRuntime() const;
    bool runtimeIsSet() const;
    void unsetRuntime();
    void setRuntime(int32_t value);

    /// <summary>
    /// Collection?
    /// </summary>
    utility::string_t getSet() const;
    bool setIsSet() const;
    void unsetset();
    void setSet(const utility::string_t& value);

    std::vector<std::shared_ptr<Models_Studio>> getStudios() const;
    bool studiosIsSet() const;
    void unsetStudios();
    void setStudios(const std::vector<std::shared_ptr<Models_Studio>>& value);

    utility::string_t getTagline() const;
    bool taglineIsSet() const;
    void unsetTagline();
    void setTagline(const utility::string_t& value);

    utility::string_t getTitle() const;
    bool titleIsSet() const;
    void unsetTitle();
    void setTitle(const utility::string_t& value);

    /// <summary>
    /// path/url
    /// </summary>
    utility::string_t getTrailer() const;
    bool trailerIsSet() const;
    void unsetTrailer();
    void setTrailer(const utility::string_t& value);

    utility::string_t getUpdatedAt() const;
    bool updatedAtIsSet() const;
    void unsetUpdatedAt();
    void setUpdatedAt(const utility::string_t& value);

    int32_t getYear() const;
    bool yearIsSet() const;
    void unsetYear();
    void setYear(int32_t value);


protected:
    std::vector<std::shared_ptr<Models_Actor>> m_Actors;
    bool m_ActorsIsSet;

    utility::string_t m_Banner;
    bool m_BannerIsSet;

    utility::string_t m_Certification;
    bool m_CertificationIsSet;

    utility::string_t m_CreatedAt;
    bool m_CreatedAtIsSet;

    std::shared_ptr<Gorm_DeletedAt> m_DeletedAt;
    bool m_DeletedAtIsSet;

    std::vector<std::shared_ptr<Models_Actor>> m_Directors;
    bool m_DirectorsIsSet;

    utility::string_t m_Filepath;
    bool m_FilepathIsSet;

    std::vector<std::shared_ptr<Models_Genre>> m_Genres;
    bool m_GenresIsSet;

    int32_t m_Id;
    bool m_IdIsSet;

    std::vector<std::shared_ptr<Models_Language>> m_Languages;
    bool m_LanguagesIsSet;

    utility::string_t m_OriginalTitle;
    bool m_OriginalTitleIsSet;

    utility::string_t m_Plot;
    bool m_PlotIsSet;

    utility::string_t m_Poster;
    bool m_PosterIsSet;

    std::vector<std::shared_ptr<Models_Actor>> m_Producers;
    bool m_ProducersIsSet;

    double m_Rating;
    bool m_RatingIsSet;

    std::shared_ptr<Object> m_Resume;
    bool m_ResumeIsSet;

    int32_t m_Runtime;
    bool m_RuntimeIsSet;

    utility::string_t m_set;
    bool m_setIsSet;

    std::vector<std::shared_ptr<Models_Studio>> m_Studios;
    bool m_StudiosIsSet;

    utility::string_t m_Tagline;
    bool m_TaglineIsSet;

    utility::string_t m_Title;
    bool m_TitleIsSet;

    utility::string_t m_Trailer;
    bool m_TrailerIsSet;

    utility::string_t m_UpdatedAt;
    bool m_UpdatedAtIsSet;

    int32_t m_Year;
    bool m_YearIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Movie_H_ */
