/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Models_Profile.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Profile_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Profile_H_

#include <boost/optional.hpp>

#include "danflix_client/ModelBase.h"

#include "danflix_client/model/Gorm_DeletedAt.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Gorm_DeletedAt;


class  Models_Profile
    : public ModelBase
{
public:
    Models_Profile();
    virtual ~Models_Profile();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Models_Profile members


    utility::string_t getAvatar() const;
    bool avatarIsSet() const;
    void unsetAvatar();
    void setAvatar(const utility::string_t& value);

    utility::string_t getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();
    void setCreatedAt(const utility::string_t& value);

    std::shared_ptr<Gorm_DeletedAt> getDeletedAt() const;
    bool deletedAtIsSet() const;
    void unsetDeletedAt();
    void setDeletedAt(const std::shared_ptr<Gorm_DeletedAt>& value);

    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    /// <summary>
    /// parent, kid
    /// </summary>
    utility::string_t getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(const utility::string_t& value);

    utility::string_t getUpdatedAt() const;
    bool updatedAtIsSet() const;
    void unsetUpdatedAt();
    void setUpdatedAt(const utility::string_t& value);


protected:
    utility::string_t m_Avatar;
    bool m_AvatarIsSet;

    utility::string_t m_CreatedAt;
    bool m_CreatedAtIsSet;

    std::shared_ptr<Gorm_DeletedAt> m_DeletedAt;
    bool m_DeletedAtIsSet;

    int32_t m_Id;
    bool m_IdIsSet;

    utility::string_t m_Name;
    bool m_NameIsSet;

    utility::string_t m_Type;
    bool m_TypeIsSet;

    utility::string_t m_UpdatedAt;
    bool m_UpdatedAtIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Models_Profile_H_ */
