/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Models_MediaProgress.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Models_MediaProgress_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Models_MediaProgress_H_

#include <boost/optional.hpp>

#include "danflix_client/ModelBase.h"

#include "danflix_client/Object.h"
#include "danflix_client/model/Gorm_DeletedAt.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Gorm_DeletedAt;


class  Models_MediaProgress
    : public ModelBase
{
public:
    Models_MediaProgress();
    virtual ~Models_MediaProgress();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Models_MediaProgress members


    utility::string_t getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();
    void setCreatedAt(const utility::string_t& value);

    std::shared_ptr<Gorm_DeletedAt> getDeletedAt() const;
    bool deletedAtIsSet() const;
    void unsetDeletedAt();
    void setDeletedAt(const std::shared_ptr<Gorm_DeletedAt>& value);

    bool isFinished() const;
    bool finishedIsSet() const;
    void unsetFinished();
    void setFinished(bool value);

    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    /// <summary>
    /// Unified field for clients
    /// </summary>
    std::shared_ptr<Object> getMedia() const;
    bool mediaIsSet() const;
    void unsetMedia();
    void setMedia(const std::shared_ptr<Object>& value);

    int32_t getMediaId() const;
    bool mediaIdIsSet() const;
    void unsetMediaId();
    void setMediaId(int32_t value);

    /// <summary>
    /// \&quot;movie\&quot;, \&quot;episode\&quot;, \&quot;game\&quot;, \&quot;tv\&quot;
    /// </summary>
    utility::string_t getMediaType() const;
    bool mediaTypeIsSet() const;
    void unsetMediaType();
    void setMediaType(const utility::string_t& value);

    int32_t getProfileId() const;
    bool profileIdIsSet() const;
    void unsetProfileId();
    void setProfileId(int32_t value);

    /// <summary>
    /// Seconds
    /// </summary>
    int32_t getProgress() const;
    bool progressIsSet() const;
    void unsetProgress();
    void setProgress(int32_t value);

    /// <summary>
    /// Seconds
    /// </summary>
    int32_t getTotal() const;
    bool totalIsSet() const;
    void unsetTotal();
    void setTotal(int32_t value);

    utility::string_t getUpdatedAt() const;
    bool updatedAtIsSet() const;
    void unsetUpdatedAt();
    void setUpdatedAt(const utility::string_t& value);


protected:
    utility::string_t m_CreatedAt;
    bool m_CreatedAtIsSet;

    std::shared_ptr<Gorm_DeletedAt> m_DeletedAt;
    bool m_DeletedAtIsSet;

    bool m_Finished;
    bool m_FinishedIsSet;

    int32_t m_Id;
    bool m_IdIsSet;

    std::shared_ptr<Object> m_Media;
    bool m_MediaIsSet;

    int32_t m_MediaId;
    bool m_MediaIdIsSet;

    utility::string_t m_MediaType;
    bool m_MediaTypeIsSet;

    int32_t m_ProfileId;
    bool m_ProfileIdIsSet;

    int32_t m_Progress;
    bool m_ProgressIsSet;

    int32_t m_Total;
    bool m_TotalIsSet;

    utility::string_t m_UpdatedAt;
    bool m_UpdatedAtIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Models_MediaProgress_H_ */
