/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Routes_SpecificProgressRequest.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_SpecificProgressRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_SpecificProgressRequest_H_

#include <boost/optional.hpp>

#include "danflix_client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Routes_SpecificProgressRequest
    : public ModelBase
{
public:
    Routes_SpecificProgressRequest();
    virtual ~Routes_SpecificProgressRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Routes_SpecificProgressRequest members


    bool isFinished() const;
    bool finishedIsSet() const;
    void unsetFinished();
    void setFinished(bool value);

    int32_t getProgress() const;
    bool progressIsSet() const;
    void unsetProgress();
    void setProgress(int32_t value);

    int32_t getTotal() const;
    bool totalIsSet() const;
    void unsetTotal();
    void setTotal(int32_t value);


protected:
    bool m_Finished;
    bool m_FinishedIsSet;

    int32_t m_Progress;
    bool m_ProgressIsSet;

    int32_t m_Total;
    bool m_TotalIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_SpecificProgressRequest_H_ */
