/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Routes_ImportGamesRequest.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_ImportGamesRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_ImportGamesRequest_H_

#include <boost/optional.hpp>

#include "danflix_client/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Routes_ImportGamesRequest
    : public ModelBase
{
public:
    Routes_ImportGamesRequest();
    virtual ~Routes_ImportGamesRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Routes_ImportGamesRequest members


    utility::string_t getPath() const;
    bool pathIsSet() const;
    void unsetPath();
    void setPath(const utility::string_t& value);


protected:
    utility::string_t m_Path;
    bool m_PathIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_ImportGamesRequest_H_ */
