/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Routes_ProgressRequest.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_ProgressRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_ProgressRequest_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "danflix_client/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Routes_ProgressRequest
    : public ModelBase
{
public:
    Routes_ProgressRequest();
    virtual ~Routes_ProgressRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Routes_ProgressRequest members

    enum class TypeEnum
    {
        MOVIE,
        EPISODE,
        GAME,
        TV,
    };

    TypeEnum toTypeEnum(const utility::string_t& value) const;
    const utility::string_t fromTypeEnum(const TypeEnum value) const;


    bool isFinished() const;
    bool finishedIsSet() const;
    void unsetFinished();
    void setFinished(bool value);

    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    /// <summary>
    /// Seconds
    /// </summary>
    int32_t getProgress() const;
    bool progressIsSet() const;
    void unsetProgress();
    void setProgress(int32_t value);

    /// <summary>
    /// Seconds
    /// </summary>
    int32_t getTotal() const;
    bool totalIsSet() const;
    void unsetTotal();
    void setTotal(int32_t value);

    TypeEnum getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(const TypeEnum value);


protected:
    bool m_Finished;
    bool m_FinishedIsSet;

    int32_t m_Id;
    bool m_IdIsSet;

    int32_t m_Progress;
    bool m_ProgressIsSet;

    int32_t m_Total;
    bool m_TotalIsSet;

    TypeEnum m_Type;
    bool m_TypeIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_ProgressRequest_H_ */
