/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Routes_TokenRequest.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_TokenRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_TokenRequest_H_

#include <boost/optional.hpp>

#include "danflix_client/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Routes_TokenRequest
    : public ModelBase
{
public:
    Routes_TokenRequest();
    virtual ~Routes_TokenRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Routes_TokenRequest members


    utility::string_t getPin() const;
    bool pinIsSet() const;
    void unsetPin();
    void setPin(const utility::string_t& value);

    int32_t getProfileId() const;
    bool profileIdIsSet() const;
    void unsetProfileId();
    void setProfileId(int32_t value);


protected:
    utility::string_t m_Pin;
    bool m_PinIsSet;

    int32_t m_ProfileId;
    bool m_ProfileIdIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_TokenRequest_H_ */
