/**
 * Danflix API
 * Danflix Media Server API
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.19.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Routes_GenerationInfo.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_GenerationInfo_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_GenerationInfo_H_

#include <boost/optional.hpp>

#include "danflix_client/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Routes_GenerationInfo
    : public ModelBase
{
public:
    Routes_GenerationInfo();
    virtual ~Routes_GenerationInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Routes_GenerationInfo members


    utility::string_t getEraName() const;
    bool eraNameIsSet() const;
    void unsetEraName();
    void setEraName(const utility::string_t& value);

    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    utility::string_t getYears() const;
    bool yearsIsSet() const;
    void unsetYears();
    void setYears(const utility::string_t& value);


protected:
    utility::string_t m_EraName;
    bool m_EraNameIsSet;

    int32_t m_Id;
    bool m_IdIsSet;

    utility::string_t m_Name;
    bool m_NameIsSet;

    utility::string_t m_Years;
    bool m_YearsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Routes_GenerationInfo_H_ */
